### ISSUE TITLE
Vorschriften Lagersport/Trekking nur bei Lager mit J+S-Rahmen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#125]
Damit ein Lager eingereicht werden kann, muss der AL die drei Häkchen ganz unten im Lager (Reiter "Allgemein") setzen - auch bei "Für J+S-Lager: Die aktuellen Vorschriften des Sportfachs Lagersport/Trekking sind mir bekannt und werden eingehalten". 

Was dort aber nicht stimmt:
Wenn bei "J+S-Rahmen" angegeben wurde, dass es sich um kein J+S-Lager handelt, muss die Checkbox trotzdem gesetzt werden.

Diese sollte nur notwendig sein, wenn es sich auch um ein J+S-Lager handelt.

**Comment by carlobeltrame** [comment]
Ich dachte immer das bezieht sich auf den Satz in Abschnitt 2c) im [Reglement über die Vorbereitung und Durchführung von Lagern](https://github.com/hitobito/hitobito_pbs/files/3831438/2085.04.de-Reglement.ueber.die.Vorbereitung.und.Durchfuehrung.von.Lagern-V20181111-Bkom.pdf) der PBS:
> Als Sicherheitsbestimmungen für alle Lager (mit oder ohne Anmeldung bei J+S) gelten die Sicherheitsrichtlinien von J+S, welche im J+S-Handbuch Lagersport/Trekking und im Merkblatt Unfallprävention von J+S festgehalten sind.

**Comment by Michael-Schaer** [comment]
Merci für die Rückmeldung! Ich melde mich dazu nochmal.

**Comment by Michael-Schaer** [comment]
Wie Cosinus beschreibt, haben wir da den Kontext verwechselt.
