### ISSUE TITLE
Export BSV Failure

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_pbs#14]
Auf der Kursliste (https://db.scout.ch/de/list_courses) führt ein BSV Export zu einem 500 Fehler, wenn man Basiskurs Wolfsstufe für das Jahr 2016 exportiert.

Auf Integration kommt kein solcher Fehler, das heisst, es muss mit den zugrundeliegenden Daten auf der Produktion zu tun haben.

**Comment by puzzleitc** [comment]
```
[35d2580e-32c9-4b01-bd3b-90b8eba57f22] Completed 500 Internal Server Error in 4136ms (ActiveRecord: 106.5ms)
[35d2580e-32c9-4b01-bd3b-90b8eba57f22] ** [Airbrake] Success: Net::HTTPOK
[35d2580e-32c9-4b01-bd3b-90b8eba57f22] 
NoMethodError (undefined method `each' for nil:NilClass):
  app/domain/export/csv/generator.rb:27:in `block in generate'
  app/domain/export/csv/generator.rb:27:in `generate'
  app/domain/export/csv/generator.rb:21:in `initialize'
  app/domain/export/csv/base.rb:20:in `new'
  app/domain/export/csv/base.rb:20:in `export'
```

**Comment by hupf** [comment]
Mit https://github.com/hitobito/hitobito/commit/e25b203afd57a9cc6e36316d85bedc4d635c7195 bereits gefixt, aber noch nicht deployed, siehe auch:
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/56f3a4dfde77482c60005ddc
