### ISSUE TITLE
Lagerhierarchie

### ISSUE THREAD

**Issue by merlinscout** [hitobito/hitobito_pbs#143]
Funktion "An übergeordnetes Lager anschliessen" funktioniert nicht. Es gibt jedes mal eine Fehlermeldung.

**Comment by Vento-Nuenenen** [comment]
Mipmöp: hier der Fehler...

<img width="479" alt="Bildschirmfoto 2020-02-03 um 15 43 26" src="https://user-images.githubusercontent.com/35610192/73662555-51d55780-469c-11ea-9284-ad4ed73c396f.png">

<img width="1440" alt="Bildschirmfoto 2020-02-03 um 15 43 34" src="https://user-images.githubusercontent.com/35610192/73662559-54d04800-469c-11ea-99be-71e7e996ba20.png">

Müsste ich raten, würde ich aufs Routing tippen...

**Comment by carlobeltrame** [comment]
Merci für die Meldung! Ich kann das aber nicht reproduzieren, auf der Integrationsumgebung konnte ich ohne Probleme den Event 1286 an das Übergeordnete Lager 1289 anschliessen. Könnt ihr eure genauen Schritte zum Reproduzieren aufzählen?

**Comment by Vento-Nuenenen** [comment]
Moin Cosinus
Das passiert glaub ich nur wenn ein neues Lager direkt an ein Überlager angehängt wird. EIn bereits erstelltes scheint wohl zu klappen...

**Comment by Michael-Schaer** [comment]
@merlinscout @lukaseisenring @Vento-Nuenenen Merci fürs Melden und Dokumentieren

Ich kann das Problem auch nachstellen, wenn ich neue Lager erstelle.

**Comment by Vento-Nuenenen** [comment]
Der Fehler ist in https://github.com/hitobito/hitobito_pbs/blob/c24c61cdd59968398382011b10af8f1df9d3dd8c/app/controllers/supercamps_controller.rb#L53-L56
Dort werden die potentiellen Überlager rausgesucht. Da aber ein nicht erstelltes Lager keine ID hat, gibts nen fehler.

**Comment by carlobeltrame** [comment]
Merci allenn für die Contribution! Ich habe das Problem gefixt, Tests dafür geschrieben und auf Integration (https://pbs.puzzle.ch) deployed. @Michael-Schaer @merlinscout @lukaseisenring @Vento-Nuenenen könntet ihr dort nochmals testen?

**Comment by Vento-Nuenenen** [comment]
Von mir  aus siehts jetzt gut aus.

**Comment by Michael-Schaer** [comment]
Ich habe heute nochmal das Anhängen von Lagern über mehrere Stufen gestestet. Dabei bin ich auf keine Fehler mehr gestossen.
