### ISSUE TITLE
Falsche Links in der Hilfe-Seite

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#150]
Der [PR 144](https://github.com/hitobito/hitobito_pbs/pull/144/) wurde irgendwo auf dem Weg zum letzten Release überschrieben.

Siehe Integration oder Produktion, folgende Seite:
https://db.scout.ch/fr/help

Dort sind wieder die Links auf scout.ch drin, anstatt die Dynamischen, die ich selber ändern kann.

**Comment by carlobeltrame** [comment]
[Die Änderungen](https://github.com/hitobito/hitobito_pbs/blob/master/config/locales/views.pbs.fr.yml#L261) sind im Master drin, aber beim Deployen wurde wohl von Transifex [gepullt](https://github.com/hitobito/hitobito_pbs/commit/65568ccc749ec17f31adaa33ad2c784e2ba5e8b4) ohne zuerst zu pushen. Habe jetzt gepusht, und in Transifex sind jetzt die neuen Links drin. Somit sollte das beim nächsten Deployment behoben sein.
