### ISSUE TITLE
Erweiterter Haushalte-Export klappt nur bei Gruppe 1

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#152]
Habe gerade einen Bug in meinem Hackathon-Feature gefunden (https://github.com/hitobito/hitobito_pbs/pull/134)

Bei der Root-Gruppe klappt der Haushalts-Export mit Details
https://pbs.puzzle.ch/de/groups/1/people.xlsx?household_details=true

Bei den Untergruppen wird aber die normale Adressliste exportiert:
https://pbs.puzzle.ch/de/groups/394/people.xlsx?household_details=true

Da muss ich wohl noch mal über die Bücher.

**Comment by simfeld** [comment]
Ich kann das Verhalten so nicht reproduzieren. Bei den angegebenen Links erhalte ich in beiden Fällen die gewünschten weiteren Spalten (Korrespondenzsprache, Kantonalverband, Id, Id der Hauptebene, Firmenname, Firma).

**Comment by Michael-Schaer** [comment]
Jetzt wird die richtige Liste exportiert. Ev. war das ein Caching-Problem. Hoffen wir, dass es auf Produktion von Anhieb an klappt :)

**Comment by Michael-Schaer** [comment]
Das Problem tritt auf Produktion nicht mehr auf.
