### ISSUE TITLE
wording Rollen

### ISSUE THREAD

**Issue by brotibus** [hitobito/hitobito_pbs#156]
Momentan sind die im persönlichen Profil ersichtlichen Rollen der Personen nur in der männlichen Form verfügbar, viele der Benutzenden sind jedoch nicht männlich. 
Wäre es möglich diese anders zu formulieren? 
Von:
Adressverwalter
Einheitsleiter
...
Zu: 
Adressverwalter * in
Einheitsleiter * in
...

**Comment by kronn** [comment]
Dies ist durch die Übersetzungen einstellbar. Vermutlich kann @Michael-Schaer hier einen passenden Kontakt liefern, um die Formulierung nicht nur in der deutschen Version, sondern auch in den anderen Sprachen anzupassen.
