### ISSUE TITLE
Zugriffsberechtigungen Kursfreigaben Fremdkurse (PBS Ref. AKom#1)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#16]
**Beschreibung Ist-Situation:** 

die Rolle Ausbildungsverantwortlicher kann aktuell die offenen Empfehlungen/Freigaben (Ansicht pending_approvals) von sämtlichen Kantonalverbänden ansehen und bearbeiten.

dasselbe bei Rolle Abteilungsleitung kann bei jeder anderen Pfadiabteilung Kursfreigaben einsehen und "anpassen

**Soll-Situation:** Die Rolle Ausbildungsverantwortlicher darf aber nur die offenen Freigaben für die An-meldungen aus der eigenen Gruppe ansehen und bearbeiten. Die Ansichtsberechtigung muss entsprechend angepasst werden.

Für alle Rollen mit Ability Approve Application gilt, Freigaben sollen nur dort gemacht werden, wo ich diese Rolle auch inne habe, also auf genau der Abteilung oder auf dem Kanton wo ich die Rolle habe, auch nicht von "Kindergruppen oder Ebenen"

---

## Beispiel

Als Ausbildungsverantwortlicher Kanton Bern, kann ich auch auf Kanton Zürich Kursfreigaben sehen (pending approvals) und auch freigeben.

**Comment by RolandStuder** [comment]
Bitte schätzen

Ist das bei Jubla gleich implementiert? Kommt das vom Youth Wagon?

**Comment by codez** [comment]
pending_approvals gibt es nur im PBS Wagon

**Comment by RolandStuder** [comment]
Betrifft Jubla nicht, da sie keine Pending Approvals haben.

**Comment by philippekeller** [comment]
OK
