### ISSUE TITLE
Ladezeit group_health - Endpunkt "groups"

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#160]
Hier ein Feedback zur HealthCheck-Schnittstelle. Das sollten wir bei Gelegenheit verbessern. Womöglich ist das auch ein allgemeines Muster bei den Schnittstellen, das ist zusätzlich zu überprüfen.

```
Die Daten der Schnittstele scheinen alle wie erwartet anzukommen.
Mir ist nur aufgefallen, dass der Request für den Endpunkt 'groups'
(https://pbs.puzzle.ch/group_health/groups) massiv länger dauert, als die anderen. 
Konkret habe ich herausgefunden, dass die Requests bis zur letzten Seite 
ca 4-5 Sekunden dauernd die letzte Seite 10-12 Sekunden.

Beispiel 1: 100 Records, Pagination 30:

1. Request 1-20: 4-5 Sekunden
2. Request 21-40: 4-5 Sekunden
3. Request 41-60: 4-5 Sekunden
4. Request 61-80: 4-5 Sekunden
5. Request 81-100: 10-12 Sekunden

Beispiel 2: 100 Records, Pagination 50:
1. Request 1-50: 4-5 Sekunden
2. Request 51-100: 10-12 Sekunden

Die requests auf allen anderen Endpunkten (roles, people, courses, ...) gehen alle, 
auch paginated, sehr schnell (<0.8 Sekunden).

Ich hoffe das Feedback ist dir bei der Suche nach der Ursache hilfreich. [...]
```

**Comment by Michael-Schaer** [comment]
Hier noch eine Info vom Projektteam HealthCheck. Womöglich hilft diese auch noch weiter. Bitte mit Priorität behandeln, da die Weiterentwicklung im Projekt abhängig davon ist.

> Lokal stehen uns nur die Seed-Daten zur Verfügung, so dass wir den Fehler nicht reproduzieren und analysieren können. Es fällt aber auf, dass es sich bei diesem Endpunkt um den einzigen handelt, bei dem das Query so erweitert wird, dass es zu zwei Full Table Scans auf der Tabelle groups kommt (https://github.com/hitobito/hitobito_pbs/blob/master/app/controllers/group_health_controller.rb, Zeile 35).

**Comment by carlobeltrame** [comment]
Ich habe die Datenbankabfrage für diesen Endpoint optimiert und einen Index für eine Spalte hinzugefügt. Bitte erneut auf Integration testen, es geht jetzt deutlich schneller.

**Comment by carlobeltrame** [comment]
Habe gleich noch auf Integration bei allen 160 Abteilungen das group_health Opt-In-Flag aktiviert, so könnt ihr auch auf Integration mit etwas realistischeren Datenmengen testen.

**Comment by c0depwn** [comment]
@carlobeltrame Funktioniert auf der Integrationsumgebung wie erwartet. Die Ladezeit ist deutlich kürzer (<4s für alle ~650 Gruppen).

**Comment by Michael-Schaer** [comment]
@carlobeltrame Merci vielmal für den Fix! Könntest du einen Patch für die Produktion machen, und mich informieren, wenn die Änderung live ist?

**Comment by carlobeltrame** [comment]
@Michael-Schaer @c0depwn der Fix ist jetzt auf Produktion aufgeschaltet.
