### ISSUE TITLE
ODER-Verknüpfung für Teilnahmebedingungen (PBS Ref. AKom#2)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#17]
**Beschreibung:** Überprüfung der Teilnahmekriterien: wir sollten situativ sowohl UND als auch ODER-Verknüpfungen zwischen den Aufnahmebedingungen für Kurse definieren können. Aktuell nur UND-Verknüpfungen möglich. Es gibt auch Combos im Sinne von (A+B) oder (A+C)

**Bemerkung:** Das UND und ODER-Verknüpfungen nötig stand auch in den ursprünglichen Spezifikationen (Kap. 8.3). 

**Beispiel:**
![i2](https://cloud.githubusercontent.com/assets/9968417/18663244/fb641b8c-7f1d-11e6-9bf0-8ea5160fd755.png)

--

**Variante A: Beliebige Kombinationen zulassen siehe Mockup** soll umgesetzt werden
Variante B: Nur wählen ob Und oder Oder Verknüpfüung gilt

![17 oder verknupfung](https://cloud.githubusercontent.com/assets/194364/22775616/cbeb2aea-eeac-11e6-9d82-61df2cf2ac70.png)

Weitere Kriterien:

* Sinnvolle Darstellung der Bedingung (korrekter Text auf Kursinfoseite)

**Comment by RolandStuder** [comment]
Es gibt auch Combos im Sinne von (A+B) oder (A+C)

**Comment by RolandStuder** [comment]
Bitte schätzen mit beiden Varianten

**Comment by RolandStuder** [comment]
Jubla ist wohl nicht betroffen, weil bei ihnen niemand nur eine Kindersportanerkennung habe.

**Comment by codez** [comment]
Variante A umsetzen

**Comment by philippekeller** [comment]
OK
