### ISSUE TITLE
Export NDBJS für MAC (PBS Ref. AKom#4)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#18]
**Beschreibung:** Der CSV Export führt bei MACs teilweise zu Problemen (Sonderzeichen, Umlaute).

Evtl. Encoding explizit wählbar machen, oder auf Benutzer festlegen?

## Lösungsmöglichkeiten:

* A: Im Exportmenü jede Exportmöglichkeit verdoppeln. z. B. NBJS (Mac)
* B: In Einstellungen neuer Menüpunkt dort Encoding wählen können
* C: XLSX Export anbieten im Exportmenü

## Entscheidung:

Sicherstellen, dass alle Personenexporte nun auch als XLSX verfügbar sind. Beachte PR 
https://github.com/hitobito/hitobito/pull/204

## Schätzung 1.5 PT

**Dieses Feature ist auf http://pbs.puzzle.ch/ zu testen!!!**

**Comment by RolandStuder** [comment]
Hier geht's auch um J+S Import, darum muss es auch mit CSV Export korrekt gehen.

**Comment by RolandStuder** [comment]
Lässt sich eigentlich nicht lösen, man muss einfach jeweils das richtige Encoding wählen.

**Comment by RolandStuder** [comment]
@philippekeller Abklären, ob sich das lohnt. Wichtig nur Anzeige auf z. B. Mac wird anders sein. Evtl. gibt es beim Reimport nach NDBJS wieder Probleme (dass NDBJS das File dann mit dem anderen Encoding erwartet).

**Comment by RolandStuder** [comment]
Heute machen die Coaches oft noch Anpassungen, da sie ja keine Schreibberechtigung auf die Kursteilnehmer haben. Beim Upload in der SportDB können sie im Preview ein Encoding auswählen, dort haben sie also keine Mühe.

Eine Variante wäre auch ein Raten des korrekten Encodings aufgrund des User Agents.

**Comment by codez** [comment]
Wurde im Master Branch hinzugefügt.

**Comment by hupf** [comment]
Für die Insieme XLS Exports das Auto Filter Setting konfigurierbar gemacht.

**Comment by philippekeller** [comment]
OK
