### ISSUE TITLE
Automatische Mails: gewählte Anrede nicht berücksichtigt (PBS Ref. AKom#5)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#19]
Beschreibung: die Anrede in den Personendaten wird für die automatischen Mails nicht konsequent angewendet.

Problem reproduzieren:
User http://pbsc-vbl.puzzle.ch/de/groups/111/people/2187.html hat die Anrede «Liebe(r) [Pfadiname]» ausgewählt und meldet sich für einen Kurs an.

Im automatischen Mail wird die Anrede [Vorname] verwendet.
![i5](https://cloud.githubusercontent.com/assets/9968417/18663322/562963f6-7f1e-11e6-8ff6-01cba7bb1597.png)

Siehe auch: PBS Ref.#19 (Pfadiname auf Etikettendruck)

## Lösung:

* Neuer Platzhalter für Texte für Email im Adminbereich {recipient-name-with-salutation}

**Comment by codez** [comment]
* Tests für die überschriebenen Placeholders/Mailers
* In den Wagon Seeds würde ich die Core CustomContents nicht nochmals seeden, schliesslich sind sie auch dort als `seed_once` drin. Die Migrations sollte ja reichen zum Anpassen. Oder nicht?
* Copyright + encoding Headers in alle neuen Dateien, bestehende mit aktuellem Jahr aktualisieren.
* Features immer als User durchspielen!!!

**Comment by kronn** [comment]
- Tests sind hinzugefügt
- Die Seeds im Wagon sind unter anderem für die Tests wichtig. Da ich weiterhin auch nicht wissen kann, in welcher Reihenfolge seeding und migrations laufen, würde ich es an beiden Stellen haben wollen.
- Copyright/Encoding-Header habe ich in allen Dateien angepasst, die ich bearbeitet habe.

**Comment by philippekeller** [comment]
Nicht OK: Anrede bei Anmeldung gewählt „Lieber Pfadiname“, im Mail aber „Hallo Sina“

**Comment by RolandStuder** [comment]
@philippekeller : Ich habe es für einen Fall getestet und dort hat es funktioniert. Kannst du mir bitte genauere Angaben machen mit welcher Person, welches Mail, in welcher Situation hätte ausgelöst werden sollen.

Vorraussetzungen:
* Im richtigen Mail ist der richtige Platzhalter: {recipient-name-with-salutation}
* Auf Empfänger ist eine Anrede gewählt
* Empfänger hat einen Pfadinamen hinterlegt

Mein Test mit Anmeldung von dieser Person http://pbs.puzzle.ch/de/groups/2/people/779.html beim Anlass http://pbsk.puzzle.ch/de/groups/1/events/1 hat zum richtigen Email geführt.

Wir brauchen also von euch die genauen Angaben, in welchem Fall es nicht geklappt hat. Am besten mit URL von Emailtext im Adminiinterface, URL wo du die Aktion machst, welche nicht korrekt ausfführt. Und URL von der Person mit der du das ausführst.

**Comment by philippekeller** [comment]
Du hast Recht, es funktioniert. Bei der betreffenden Email war der Platzhalter noch nicht richtig im E-Mail-Text, jedoch korrekterweise verfügbar. Nach dem Einfügen hat dann alles super funktioniert. Sorry, mea culpa.

Es gibt also hier kein Problem. OK.
