### ISSUE TITLE
Add birthdate to people JSON endpoint

### ISSUE THREAD

**Issue by yannbolliger** [hitobito/hitobito_pbs#193]
This is a feature request for the `people.json` endpoint.

The current serialisation format is 
```json
    {
      "id": "99999999",
      "type": "people",
      "href": "https://db.scout.ch/de/groups/1234/people/5678.json",
      "first_name": "Röbu",
      "last_name": "Baden-Powell",
      "nickname": "BiPi",
      "company_name": "",
      "company": false,
      "email": "bipi@lords.co.uk",
      "address": "Speichergasse 11",
      "zip_code": "3011",
      "town": "Bern",
      "country": "CH",
      "picture": "https://db.scout.ch/assets/profil-HASH.png",
      "links": {
        "phone_numbers": [
          "2222222", ...
        ],
        "roles": [
          "111111", ...
        ]
      }
    },
```

There is already so much sensitive information, that it couldn't hurt to add the `birthdate`.

I am very happy to provide a PR. Will it be enough to add `:birthdate` here:
https://github.com/hitobito/hitobito/blob/409d87e8d2ee6fa358c997766922835f8c0c7183/app/serializers/people_serializer.rb#L23-L32

**Comment by carlobeltrame** [comment]
The data that is exposed partially depends on your access rights to the person (especially when you use the old personal access tokens). You can see [here](https://github.com/hitobito/hitobito/blob/409d87e8d2ee6fa358c997766922835f8c0c7183/app/serializers/people_serializer.rb#L39) that only public emails, phones and social accounts are published when the API user does not have the index_full ability.
Would it suffice for your use case to only add the birth date if the API user has `index_full` ability? If so, something like the following might work:
```
map_properties :birthdate if index_full_ability?
```
And we'd probably also want a unit test that checks that this distinction works as expected.

**Comment by yannbolliger** [comment]
My plan was to use an API token, not a personal one. But if that still makes the birthdate accessible, then my use-case is covered and I'm happy to provide the PR.

**Comment by carlobeltrame** [comment]
Sounds good to us, feel free to create a PR. :+1: 
The issue technically does concern all users of hitobito, but the PR will be there anyways, so I wouldn't worry about it.
