### ISSUE TITLE
French taged email don't export properly

### ISSUE THREAD

**Issue by sulazix** [hitobito/hitobito_pbs#2]
French taged email like :
  * Mère
  * Père 
  * Privé
  * ...
Don't export on csv file, the fields headers are presents (p.ex : "Adresse e-mail supplémentaire Mère") but cells bellow are empty.
If we change "Mère" to "E-Mail Mutter" export work perfectly

**Comment by codez** [comment]
We could reproduce the issue. The addresses are completely exported when the application language is German, but not for the other languages. We will have a look at this. Thanks for reporting.

**Comment by codez** [comment]
Fixed
