### ISSUE TITLE
Pflichtfelder bei Person für Kursanmeldung (PBS Ref. AKom#6)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#20]
**Beschreibung:** Assistenz A&B: Wenn sich ein TN für einen Kurs anmeldet, kann aber muss er gewisse Felder nicht ausfüllen. Z.B Nationalität oder Sprache, etc. Diese Informationen benötige ich aber für den Import ins FIVER. Weiter Informationen wie z.B. Geburtsdatum aus Profil sind auch zwingend notwendig.
Kursorganisatoren allgemein: weitere Daten sind für den Import in der NDBJS, bzw. SportDB notwendig (siehe Spezifikationen, Kap. 4.16). Es ist problematisch, wenn diese Informationen nicht zur Verfügung stehen oder falsch sind.

**Anpassungsvorschlag:** bei einer Kursanmeldung, vorausgefüllte Pflichtfelder mit den relevanten Perso-nendaten definieren. Wenn Personendaten unvollständig oder nicht mehr aktuell sind, kann der TN die nötigen Anpassungen an seinen Personendaten gerade bei der Kursanmeldung vornehmen. Seine Personendaten werden somit auch gerade aktualisiert. Lösung analog zum Anmeldungsprozess via Coach bei der NDBJS.

* Die Lösung von Janiss wird nur Kontaktdaten abdecken.
* Notwendig sind aber auch weitere Felder / auch custom fields aus dem Wagon
* Deshalb einfach ALLE Personenattribute bereitstellen

**Comment by RolandStuder** [comment]
Bemerkungen: Fiver ist das System das man braucht um die BSV Meldung zu machen.

**Comment by RolandStuder** [comment]
Wird vermutlich im Rahmen der Abschlussarbeit eines Lehrlings abgeschlossen.

@codez: Bitte trotzdem Aufwand schätzen. Gemäss Issue https://github.com/hitobito/hitobito/issues/144

**Comment by codez** [comment]
Ist das auf dem einzelnen Event/Kurs am richtigen Ort? Sollte das nicht eher auf die Kurstypen oder gar fix sein, damit das nicht jedes Mal von neuem konfiguriert werden muss?

**Comment by RolandStuder** [comment]
@philippekeller Wie siehst du das bezüglich dem dem letzten Kommentar? Ich möchte es eher allgemein halten, damit das auch andere bei Events so einsetzen können, wie sie das wollen.

**Comment by philippekeller** [comment]
@RolandStuder Allgemein macht schon Sinn. Es gibt zwar gewisse Felder, die sicher eher kursartspezifisch sind, dann gibt es aber auch wieder Ausnahmen. Ich denke also, es macht Sinn einfach je Event (inkl. Kurse und Lager) Pflichtfelder definieren zu können.

**Comment by RolandStuder** [comment]
* Schulklasse: unnötig
* Eintritts / Austrittsdatum: unnötig
* Geschwister in Abteilung: unnötig
* Geschwister: unnötig -> besser weg
* Zusätzliche Angaben: unnötig -> besser weg

unnötig heisst, weg oder zumindest default: nicht anzeigen

**Comment by psunix** [comment]
auf branch kurswesen
Änderungen auch im youth und pbs wagon

**Comment by philippekeller** [comment]
OK
