### ISSUE TITLE
Weitere Daten im TN-Liste-Export (PBS Ref. AKom#7)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#21]
**Beschreibung:** Weitere Daten im Export der TN-Liste von einem Kurs (Export > CSV > Alle Angaben) integrieren:
-   Abteilungsname
-   Empfehlungen (inkl. schriftliche Kommentare) von allen Empfehlungsinstanzen
-   Kontaktdaten der empfehlenden Instanz

Kritisch und am Meisten gefragt ist die Abteilungsname (Prio 1). Weitere Informationen in der Aufzählung hier oben sind auch relevant, können jedoch mit einer tieferen Priorität betrachtet werden.

edit: "Zusätzliche Angaben, werden bereits exportiert."

**Comment by philippekeller** [comment]
"Abteilungsname" nicht nur in Exportliste, sondern auch direkt beim der Anmeldung und in der Teilnehmer-Übersicht anzeigen wäre noch besser..

**Comment by RolandStuder** [comment]
Issue wird geschlossen zugunsten von #50 und #51
