### ISSUE TITLE
Empfehlungskommentare strukturiert und kursart-spezifisch (PBS Ref. AKom#8) 12h

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#22]
**Beschreibung:** Bei der Empfehlung von Kursteilnehmenden muss/kann die Empfehlungsinstanz einen Kommentar eingeben. Vor der Einführung von MiData stand dieser Kommentar in Form von mehreren expliziten Fragen auf dem Papierformular.
![i8](https://cloud.githubusercontent.com/assets/9968417/18663418/bac28504-7f1e-11e6-87cf-d6d7afc5fc8f.png)

Mit den Anmeldungen via MiData besteht das Bedürfnis weiterhin, diese Informationen von der Empfeh-lungsinstanz zu erhalten.  

**Anpassungsvorschlag:** Für jeden Kurs gibt es ein Kommentarfeld wie bisher. Zusätzlich kann für jeden Kursart im Admin-Bereich beliebig viele weitere Textfelder definiert. Die Legende der zusätzlichen Text-felder kann im Admin-Bereich in drei Sprachen definiert werden und wird in der Sprache der Empfeh-lungsinstanz angezeigt. Die kursartspezifischen Felder sind Pflichtfelder. Das allgemeine kursartunab-hängige Kommentarfeld ist kein Pflichtfeld.

**Beispiel:** für einen Basiskurs sind mehr oder weniger die Informationen aus dem alten Papierformular relevant. Die Empfehlungsfelder werden entsprechend im Admin-Bereich für den Kursart «Basiskurs» eingestellt. Für ein Topkurs werden keine besonderen Informationen von der Empfehlungsinstanz benö-tigt, hier wird nur das allgemeine kursunabhängige Kommentarfeld erscheinen.

## Entscheide

* Fixes Fragensetz! nicht kursspezifisch!
* Pflichtfelder

## Schätzung 1.5 PT (für fixes Fragenset)

**Comment by RolandStuder** [comment]
Es gibt Vereinfachungsmöglichkeiten, bitte angeben, wieviel man einsparen könnte, wenn man

* Nicht kurspezifische Angaben hat, sondern nur wählen kann, ob man allgemeines Kommentarfeld oder detaillliertes Formular will und Formular fix aus den obenstehenden Fragen besteht.

**Comment by codez** [comment]
> hier wieder die Frage, ist das im Youth Wagon oder ist das PBS Wagon. Wie flexibel sind wir hier?

Wagon ist Wagon. Spielt keine Rolle, wir müssen es einfach vor Entwicklungsbeginn wissen.

**Comment by codez** [comment]
Momentan wird die Empfehlung in einem Popover erteilt. Bei so vielen Feldern würde ich das wohl auf eine eigene Seite verlagern.

**Comment by philippekeller** [comment]
Hier noch die gewünschten Felder in Deutsch
![felder_empfehlung](https://cloud.githubusercontent.com/assets/25301123/23405036/78273bd6-fdb8-11e6-985c-2fe05b4644d3.JPG)

**Comment by RolandStuder** [comment]
Die Jubla behält diese Empfehlungen lieber weiterhin aus Datenschutzgründen auf Papier bei.

**Comment by kronn** [comment]
Ich gehe davon aus, dass das Formular für Empfehlungen **und** Ablehnungen eingebaut werden soll, da bisher auch eine Symmetrie zwischen den beiden Reaktionen besteht.

**Comment by RolandStuder** [comment]
Mach Was einfacher geht. Ablehnungen gibt es eigentlich in Realität fast nicht, ist keinwichtiger use case. 

Die Fragen machen bei Ablehnung zwar nur bedingt sinn, aber es wäre kein Problem wenn sie dort kommen. Oder? @philippekeller

**Comment by philippekeller** [comment]
Es ist okey - und ich ging auch davon aus - dass die Fragen auch bei Ablehnung kommen. Auch wenn sie dann in der Tat weniger Sinn machen.

**Comment by codez** [comment]
Der Aufwand für nicht-obligatorische Felder im Falle einer Ablehnung betrug 5 Sekunden. Ich habe dies jetzt so implementiert.

**Comment by philippekeller** [comment]
OK
