### ISSUE TITLE
Zugriffsberechtigungen für LKB anpassen (PBS Ref. AKom#9) 4h

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#23]
**Beschreibung:**

Ein LKB muss grundsätzlich über ähnliche Zugriffsberechtigungen wie ein Hauptkursleiter verfügen

Ergänzend zu den heutigen Berechtigungen:

- Kurs bearbeiten
- Empfehlungen anzeigen (Teilnehmer)
- Qualifikationen lesen (best. Ansicht read-only für Qualfikationen anpassen)

---

Nur als Referenz

-   Ergänzung Spezifikation 4.19-8:
  «Nach erfolgter Qualifikation ist die Teilnehmerliste nur für Kursorganisator sowie Kursleiter **und LKB** einsehbar.»
-   Ergänzung Spezifikation 4.19-9:
  «Die Empfehlung ist nur für den Kursorganisator (an die Rolle gebunden), den Kursleiter (an die Person gebunden), **den LKB (an die Person gebunden)** die Rollen, welche die Empfehlung abgegeben hat, und Rollen, welche übergeordnete Empfehlungen abgegeben haben, einsehbar.
-   Ergänzung Spezifikation 4.19-10:
  «Die Liste der Qualifikationen ist nur für den Kursorganisator sowie den Kursleiter **und LKB** einsehbar.»
-   Ergänzung Spezifikation 4.10-3:
  «Die Empfehlungsinstanz kann zu einer Anmeldung eine Empfehlung geben oder eine Teilnahme ablehnen. Die Empfehlung kann kommentiert werden.
  Bei der Empfehlung wird der Benutzer darauf hingewiesen, dass die Empfehlung elektronisch gespei-chert wird, für Kursorganisator (als Rolle), Kursleiter (in Person), **LKB (in Person)** und weitere Empfeh-lungsinstanzen (als Rolle) einsehbar ist. Dies gilt auch für zukünftige Kursorganisatoren und Empfeh-lungsinstanzen.»

Mit LKB ist die Event::Role gemeint und nicht die Gruppen Rolle Leiterkursbetreuer

## Schätzung 0.5 PT

**Comment by codez** [comment]
Ein LKB kann also auch den Kurs und die TN bearbeiten und Qualifikationen erteilen?

**Comment by RolandStuder** [comment]
@philippekeller Ein LKB kann also auch den Kurs und die TN bearbeiten und Qualifikationen erteilen?

**Comment by philippekeller** [comment]
Eigentlich würde eine Leseberechtigung reichen, die Frage ist, ob dies einfach geht?

**Comment by RolandStuder** [comment]
## Kommentar Jubla

Aus unserer Sicht muss der LKB keine Qualifikationen sehen können. Dies auch aus Datenschutzgründen. Warum braucht der LKB der PBS das?

## Kommentar hitobito 

- [ ] Frage bleibt offen, ob dies für Jubla ein Problem wäre.

**Comment by philippekeller** [comment]
OK
