### ISSUE TITLE
Silverscouts in der MiData oder "SiData"

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#235]
Wenn Personen nicht mehr aktiv bei der Pfadi sind, sollen sie die Möglichkeit erhalten, Mitglied bei den Silverscouts sowie lokalen Ehemaligengruppen zu werden. In diesem Prozess sollen potenzielle Mitglieder eigenständig steuern können, was mit ihren Daten passiert, welchen Gruppen sie beitreten und von wem sie kontaktiert werden dürfen.

## Gruppentyp Ehemalige
Auf den Ebenen Abteilung, Region und Kantonalverband soll ein neuer Gruppentyp "Ehemalige" eingeführt werden. Es können mehrere Ehemaligengruppen erstellt und auch ineinander verschachtelt werden (Verhalten wie bei Internen Gremien).

Rollen:
- Mitglied
- Leiter*in

## Eigener Root-Knoten für die Silverscouts
Um die Silverscouts besser von der bestehenden Struktur der PBS abzugrenzen, sollen sie einen eigenen Root-Knoten erhalten. Dabei soll die URL db.scout.ch weiterhin auf Pfadibewegung Schweiz zeigen. Die URL sisc.scout.ch soll hingegen auf die neue Silverscouts-Struktur zeigen.

Innerhalb der Silverscouts gibt es den Gruppentyp "Region". Eine Region hat folgende Rollen:
- Mitglied
- Leiter*in (mit Contact Data)

Achtung: Mitglieder sehen sich nicht gegenseitig! Sie sehen aber Leiter*innen der gleichen Region. Dies soll auch beim Export beachtet werden.

Leiter*innen sehen und bearbeiten alle Personen in der Region und haben ein Contact Data Flag.

Aktive und Ehemaligen können sich also nur via ihrer Leiter*innen vernetzen (welche ein Contact Data Flag haben). Bei Events ist es ok, wenn sich Aktive und Ehemalige gegenseitig sehen können. Ansonsten bleiben die Ebenen Silverscouts und Pfadibewegung Schweiz getrennt, Personen sehen sich gegenseitig nicht.

## Automatismus / Opt-in
Wenn jemand in der MiData die letzte Rolle verliert, soll nach 3 Monaten eine Anfrage via Mail verschickt werden. Diese Anfrage soll konfigurierbar sein und folgende Textbausteine beinhalten:

- Silverscouts-Regionen 
  - Alle Regionen anzeigen 
  - Link führt zur Anmeldung für die jeweilige Region
- Ehemaligen-Gruppen von vergangenen Rollen
  - Von allen Rollen aus gesehen nach oben durchsuchen
  - Alle Gruppen vom Gruppentyp Ehemalige anzeigen
  - Link führt zur Anmeldung für die jeweilige Ehemaligen-Gruppe

Für den Automatismus gibt es diverse Kriterien:
- Die letzte aktive Rolle der Person in dieser Gruppe und Ebene wurde gelöscht
- Es sind 3 Monate verstrichen und keine aktive Rolle wurde hinzugefügt
- Die gelöschte Rolle war mindestens 7 Tage alt (sonst wird die Rolle bei der Löschung als "Versehen" angesehen)
- Die gelöschte Rolle war nicht in einer Kindergruppe (Biber, Wölfe, Pfadi, Pio, PTA)
- Die gelöschte Rolle war nicht in einer Ehemaligengruppe
- Falls die Rolle doch in einer Kindergruppe war, muss die Person mindestens 16 Jahre alt sein. Ist kein Geburtsdatum gesetzt, wird auch keine Ehemaligen-Rolle erstellt und kein Mail versendet
- Es hat vorher noch keine Ehemaligenrolle in dieser Ebene existiert
- Die Person hat eine Haupt-E-Mailadresse

Wenn keine Rückmeldung eingeht, passiert erst mal nichts. Bei keiner Reaktion wird nach weiteren 3 Monaten ein Reminder (das gleiche Mail noch einmal) verschickt.

**Comment by carlobeltrame** [comment]
Den Modus, dass Personen in einer Gruppe nur sich selber und die Leitenden sehen dürfen, gibt es bisher (in der MiData) noch nicht. Wölfli und Pfadikinder sehen die Personenliste ihrer Gruppen bisher gar nicht. Ist es wichtig dass SilverScouts keine anderen SilverScouts sehen dürfen, aber ihre Leitenden für sie sichtbar sein müssen? Wenn ja, müssten wir Logik von den geschützten Spender-Rollen vom Cevi kopieren, und die ist bisher recht unübersichtlich, wirkt eher wie ein Hack.

Ausserdem beschreibst du, dass die Personen der SilverScouts und der Pfadibewegung Schweiz sich gegenseitig nicht sehen dürfen. Das contact_data Flag auf den Leitpersonen wird aber dazu führen, dass alle Personen in der PBS die selber ein contact_data Flag haben auch alle SilverScouts-Leitenden sehen werden, und umgekehrt. Ist euch das bewusst?

**Comment by Michael-Schaer** [comment]
Merci für das Feedback!

> Den Modus, dass Personen in einer Gruppe nur sich selber und die Leitenden sehen dürfen, gibt es bisher (in der MiData) noch nicht. Wölfli und Pfadikinder sehen die Personenliste ihrer Gruppen bisher gar nicht. Ist es wichtig dass SilverScouts keine anderen SilverScouts sehen dürfen, aber ihre Leitenden für sie sichtbar sein müssen? Wenn ja, müssten wir Logik von den geschützten Spender-Rollen vom Cevi kopieren, und die ist bisher recht unübersichtlich, wirkt eher wie ein Hack.

Nein, das ist nicht so zentral. Die Mitglieder könnten sich auch via Gruppen-Kontakt bei einer zuständigen Stelle / Regionsleitung melden.

> Ausserdem beschreibst du, dass die Personen der SilverScouts und der Pfadibewegung Schweiz sich gegenseitig nicht sehen dürfen. Das contact_data Flag auf den Leitpersonen wird aber dazu führen, dass alle Personen in der PBS die selber ein contact_data Flag haben auch alle SilverScouts-Leitenden sehen werden, und umgekehrt. Ist euch das bewusst?

Ja genau. ContactData und gemeinsame Anlässe sind als Ausnahmen ok. Sonst dürfen sich die zwei Ebenen aber nicht sehen.

**Comment by ThomasEllenberger** [comment]
@Michael-Schaer : Merci für die Bestellung der SiData.
Wir machen uns in den nächsten Wochen an die Umsetzung:
Wir planen hierzu dieses Issue als Konzeptionsissue zu verwenden und für die Umsetzung dann ein neues zu erstellen.

Dabei sind mir noch ein paar Fragen gekommen:

1. Visuelle Anpassungen: Wir gehen davon aus, dass wir für die SiData das gleiche Farbschema, Logo und Schriftart verwenden wie für die MiData. Korrekt, oder gibt es da noch andere Wünsche von euch?
2. Rollen- und Berechtigungsstruktur: Hierzu hast du dich in diesem Issue ja bereits mit Carlo ausgetauscht.
Ist es korrekt dass es auf allen Ebenen der SiData nur die beiden Rollentypen Leiter*in und Mitglied geben muss?
Ich denke es wäre super, wir könnten vorab die ganze Rollenstruktur definieren und aufzeichnen (analog der Readme unter https://github.com/hitobito/hitobito_pbs). Kannst du dir das anschauen und dies analog dieser ausformulieren? Gerne können wir das sonnst auch einmal gemeinsam machen während eines Calls.
3. SiData und MiData werden schlussendlich im gleichen Wagon sein. Folglich wird die SiData immer die gleichen Features haben wie die MiData. Ich gehe davon aus, dem seid ihr euch bewusst und das ist korrekt so.

**Comment by Michael-Schaer** [comment]
1. Ja, das gleiche Farbschema! Das Logo können wir ja selber hochladen, oder?

2. Können wir gerne zusammen anschauen. Ich stelle mir das so vor:

* SilverScouts
  * SilverScouts
     * Leitung
     * Mitglied
  *  Region
     * Leitung
     * Mitglied 

3. Ja, genau darum wollen wir auch keine speziellen "SilverScouts-Funktionen" einbauen. Einfach nur die Personen und Events verwalten, alles andere kommt dann ausserhalb von Hitobito via Oauth.

**Comment by daniel-illi** [comment]
@Michael-Schaer stellst du dir vor, dass das Mail bereits Anmeldelinks für alle relevanten Ehemaligengruppen sowie alle Silverscout Regionen enthält, oder führt der Anmeldelink auf eine Hitobito Page welche die Links enthält?

**Comment by Michael-Schaer** [comment]
Merci fürs Nachfragen: Ich habe mir vorgestellt, dass wir das via Selbstregistrierung lösen. Im Mail-Template könnten dann zwei Variablen `{SiScRegion-Links}` und `{AlumniGroup-Links}` verwendet werden. Die erste Variable enthält alle Links von SilverScouts-Regionen mit aktivierter Selbstregistrierung. Die zweite Variable enthält Links zu allen Ehemaligen-Gruppen im normalen MiData-Baum, die hierarchisch über der Person vorkommen und die Selbstregistrierung aktiviert haben. 

Macht das Sinn?

**Comment by daniel-illi** [comment]
@Michael-Schaer merci für die Antwort, ich habe das mal so ins Implementierungsticket #273 kopiert.

**Comment by daniel-illi** [comment]
Implementierungstickets:
* #270 
* #271 
* #272 
* #273

**Comment by richardjubla** [comment]
@Michael-Schaer 

Wie besprochen endet heute (juni 23) das Zeitfenster für mögliche (technische) Synergien zwischen Ehemaligen-Feature jubla und Silverscouts. Bei mir sind keine konkreten Inputs oder Aufträge eingegangen.

**Comment by ThomasEllenberger** [comment]
> Zwei Fragen:
> 
>     * Wir haben unzählige Silverscouts-Gruppen auf dem Integrationssystem. Woher kommen die und wäre die Idee nicht, dass es nur eine Hauptgruppe analog "PBS" gibt, wo wir dann die Regionen erfassen können?
> 
>     * Könntest du Hussein Kohlmann in der Testumgebung eine Rolle in der (ersten) Silverscouts-Gruppe vergeben, so dass wir die Regionen erstellen und testen können?

Ist beides erledigt.
- Die zusätzlichen Gruppen wurden fälschlicherweise durch ein Skript erstellt und sind nun gelöscht.
- Hussein Kohlmann hat die Rolle "Poweruser" auf der Dachebene der Silverscouts.
