### ISSUE TITLE
Wording: Kursleitung --> Kursleiter (PBS Ref. AKom#11)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#24]
Kurs-Rolle «Kursleitung» in «Kursleiter/-in» umbenennen (wie auch auf der NDBJS). Dieser Fehler führt auch zu falschen Erfassung von Kursleitern in MiData. In der französischen und italienischen Sprache sind keine Anpassungen nötig.

Nur im wagon-pbs umsetzen

Zusätzlich:

- Kurshelfer -> Kurshelfer/-in
- Klassenlehrer -> Klassenleher/-in

## Schätzung 1h

**Comment by RolandStuder** [comment]
## Kommentar Jubla

** Dies wollen wir auf der jubla.db auf keinen Fall anpassen. Aus unserer Sicht entspricht das nicht der Gendernorm. Ich finde es wichtig, dass dies der NDBJS zurückgemeldet wird und wir Kinder- und Jugendverbände keinen Rückschritt machen  gerne geben wir diesen Input an die PBS weiter und hoffen, dass sie sich das nochmals überlegen. **

Wir verstehen die Rückmeldung, dass diese Bezeichnungen auf der NBJS nicht ganz verständlich sind. Evtl. könnte man diese Bemerkung in Klammer setzen, dass die verschiedenen Personen dies verstehen. 

Da die NDBJS voraussichtlich bis 2020 neu programmiert wird, frage ich mich ob das wirklich sinnvoll ist. 

Was man allgemein überlegen könnte ist ob die Rollen der Kursleitung (Hauptleitung, Leitung, Küche, Kassier, Referent/in) wirklich sinnvoll sind. Dies müssten wir aber auch mal mit der AST und FGA diskutieren. Ausserdem wäre es korrekt, wenn Kassier/in ergänzt wird.

**Comment by philippekeller** [comment]
OK
