### ISSUE TITLE
Abwesenheit der Leiter/TN (PBS Ref. AKom#12)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#25]
**Beschreibung:** Die Assistenz A&B muss für die BSV-Abrechnung wissen, ob TN’s, Mitglieder der Kurs-leitung oder Kochteams den Kurs 100% besucht haben oder nur einzelne Tage dabei waren.

**Lösungsvorschlag:** unter neuem Tab «Anwesenheit» Liste aller Leitenden und TNs mit einer Spalte «Anzahl Tage Anwesenheit». Gruppierung nach Leitung, Küche und TN.
Die Felder werden mit dem Anzahl BSV-Tagen vorausgefüllt, damit der Hauptkursleiter beim Kursab-schluss nur bei Teilanwesenheiten Anpassungen vornehmen muss.
Der Anzahl BSV-Tage wird dafür bei der Kurseröffnung erfasst (Neues Feld nötig).

![i12](https://cloud.githubusercontent.com/assets/9968417/18663526/1aa9473c-7f1f-11e6-90a2-d615259c562c.png)

Vergleichbar mit https://github.com/hitobito/hitobito/issues/85

* **Ist nur für Kurse** Nur für BSV wirklich interessant, da die AWK bei J+S Kursen sowieso in der SportDB geführt werden muss. Für BSV ist die Erfassung Halbtageweise.

* Ausgabe im Teilnehmerexport "Alle Angaben"
* Oberhalb kleine Übersicht an Teilnehmertagen aufgeteilt nach Leitung (Kursleitung, Klassenlehrer, Referent/-in, Hilfsleiter), Küche und TN. Aktualisieren erst nach Speichern der Liste. Mehrfachrollen werden mehrfach aufgeführt und gezählt.

**Comment by RolandStuder** [comment]
Nur für BSV wirklich interessant, da die AWK bei J+S Kursen sowieso in der SportDB geführt werden muss. Für BSV ist die Erfassung Halbtageweise.

Insieme/Cerebral/Jubla ist evtl. auch interessiert am Feature.

* Summierte Ausgabe im Teilnehmerexport

siehe auch: https://github.com/hitobito/hitobito_insieme/issues/2

**Comment by RolandStuder** [comment]
Keine erneute Schätzung nötig. Siehe Schätzung Cerebral.

**Comment by codez** [comment]
> Kleine Übersicht an Teilnehmertag aufgeteilt nach Rollen für Weiterverarbeitung.

Nicht verstehen

**Comment by RolandStuder** [comment]
Ist von Jubla nicht erwünscht. Sie rechnen ohne Abwesenheitstage ab.

**Comment by RolandStuder** [comment]
Core oder Wagon? noch unklar

**Comment by RolandStuder** [comment]
Was wäre der Zusatzaufwand für eine allgemein Anwesenheitskontrolle?  Mit Checkboxes pro Datum?

**Comment by philippekeller** [comment]
OK
