### ISSUE TITLE
GroupHealth - Anpassungen an Schnittstelle Bestandesmeldung

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#259]
Uns sind noch einige Probleme mit der GroupHealth-Schnittstelle aufgefallen (siehe auch https://github.com/hitobito/hitobito_pbs/pull/243).

- Es erscheinen weiterhin nur die Gruppen, die ein Opt-In gemacht haben 
  - Das wurde leider auch nicht mit https://github.com/hitobito/hitobito_pbs/issues/241 gefixt
- Ein Feld "parent" wäre einfacher als selber herauszufinden, ob die Abteilungs-, Regions-, oder Kantonalverbands-ID der Parent ist
- Wir brauchen noch den Namen der Abteilung

Vorschlag für die Darstellung der Gruppen ohne Aufteilung in Kantonalverband, Region und Abteilung:

```
{
   "census_evaluations":{
      "groups":[
         {
            "group_id":3,
            "group_name":"Pfadi Kanton Solothurn",
            "group_type":"Group::Kantonalverband",
            "parent_group_id":2,
            "total":{
               "total":51,
               "f":26,
               "m":25
            },
            "f":{
               "leiter":4,
               "biber":0,
               "woelfe":3,
               "pfadis":3,
               "pios":4,
               "rover":5,
               "pta":6
            },
            "m":{
               "leiter":5,
               "biber":1,
               "woelfe":2,
               "pfadis":3,
               "pios":4,
               "rover":5,
               "pta":6
            }
         },
         {...},
         {...},
      ]
   }
}
```

## TODO
- [x] In `GroupHealthController#census_evaluations` die drei Gruppentypen in ein gemeinsames Array schreiben und gemäss Beispiel-JSON oben neu unter dem Key `"groups":` ausgeben, statt wie vorher aufgetrennt
- [x] In `GroupHealthController#census_data` zum `data` Hash neue Felder `group_name`, `group_type` und `parent_id` hinzufügen (dazu die Gruppe auch noch als Argument in census_data hineingeben werden)

**Comment by carlobeltrame** [comment]
@Michael-Schaer
Dass nur die Opt-In Abteilungen auftauchen, kann ich anhand dem aktuellen Code nicht nachvollziehen. Wir lassen aber Abteilungen weg, wenn sie kein `census_total` haben, also wenn im ausgewerteten Jahr keine Bestandesmeldung eingereicht wurde. Könnte dein Problem beim testen sein. Oder wenn der Report vom HealthCheck Team gekommen ist, könnte das Problem auch sein, dass im `/group_health/groups` Endpoint weiterhin nur die Opt-In Abteilungen kommen, und sie daher die Nicht-Opt-In Abteilungen nicht "erkennen" wenn sie die Bestandesmeldungen abrufen. Meiner Meinung nach ist das so wie es sein soll.

Den Rest habe ich so zur Umsetzung spezifiziert.
