### ISSUE TITLE
Info bei Kursabmeldung an Empfehlungsinstanz (PBS Ref. AKom#14)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#26]
**Beschreibung:** Empfehlungsinstanz soll über eine Kursabmeldung oder Ablehnung (via Kurs, nicht Ablehnung der Empfehlung) informiert werden.

Zwei Mails konfigurierbar mit Platzhaltern:

- Application URL
- Kursname / Kursurl
- Teilnehmer Name und URL
- Recipient-Name
- Recipient-Name-mit-Anrede

---

## Besprochene Fragen
 
* Wie sieht es aus mit offenen Freigaben, fallen diese Weg, bleiben die offen? => Fallen weg
* Sinnvoll wäre: Nur Personen zu informieren, welche bereits Empfehlung abgegeben haben. Aber wenn es weniger aufwändig ist, ist es auch ok, alle Empfehlungsinstanzen anzuschreiben.
* Was ist mit dem Case, ich klicke auf Link für eine Aufforderung eine Empfehlung abzugeben und Person hat sich inzwischen abgemeldet? => Nachricht: "[NAME] hat sich abgemeldet."
* Bei welchen Abmeldung, auch bei Selbstabmeldungen? Oder nur durch Verantwortliche? -> Betrifft Fremd- und allfällige Selbstabmeldungen.

## Schätzung 1 PT

**Comment by RolandStuder** [comment]
Für Jubla nicht nötig.

**Comment by RolandStuder** [comment]
@philippekeller Ein Beispielmail vorbereiten, wäre hilfreich.

**Comment by codez** [comment]
Nur die gewählten Empfehlungsinstanzen sollen Abmeldemails erhalten (siehe #28).

**Comment by psunix** [comment]
Betrifft Selbst- und auch Fremdabmeldung

**Comment by hupf** [comment]
Infos verschicken implementiert.

Mit Rolä besprochen:
* Placeholders nehmen wir die vom bereits bestehenden Mail (ohne Kursurl, Teilnehmerurl und Recipient-Name-mit-Anrede)
* Bei einem Statuswechsel passiert im Moment nichts mit den offenen Freigaben: Rolä erstellt ein eigenes Ticket dafür
* Selbstabmeldung kommt vom Core und löscht die Participation -- Rolä klärt ab ob diese Aktion bei PBS den Status auf Cancel setzten soll.

**Comment by philippekeller** [comment]
OK
