### ISSUE TITLE
Anmeldetermin bis und mit Datum (PBS Ref. AKom#15)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#27]
Beschreibung: Am Tag des Anmeldetermins ist es schon nicht mehr möglich, sich als TN für einen Kurs anzumelden. Besser wäre, dass die Anmeldungen **bis und mit** Datum des Anmeldetermins möglich sind. Grundsätzlich sollte die Handhabung bei Events, Kursen und Lager überall gleich sein.

**Comment by RolandStuder** [comment]
Betrache ich als Bug, den wir eh fixen müssen. Bitte auch schätzen.

**Comment by kronn** [comment]
@codez Ich sehe die Codeänderung leider nicht. in welchem Wagon/Branch wurde das implementiert?

**Comment by kronn** [comment]
Habe es gefunden: PBS, master-branch

**Comment by philippekeller** [comment]
Nicht OK: Gemäss meinem Test ind PBSK wie bisher, Anmeldung zum Kurs mit Anmeldeschluss am 19.4. war am 19.4. nicht mehr möglich.

**Comment by RolandStuder** [comment]
@philippekeller:  Das wurde noch auf dem Master gefixt. Und ist somit auf http://pbs.puzzle.ch/ zu testen.

**Comment by philippekeller** [comment]
OK: Dort funktioniert es prima, danke.
