### ISSUE TITLE
Empfehlungsinstanz/ frei wählen (PBS Ref. AKom#16)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#28]
**Beschreibung:** In den KV und Regionen sind die Zuständigkeiten für die Erteilung von Empfehlun-gen/Kursfreigaben unterschiedlich. Wenn eine Empfehlung aus einer Region oder aus einem KV für die Kursteilnahme nötig ist, erhalten sowohl Regionsleiter/Kantonsleiter wie auch Ausbildungsverantwortli-che eine Mail (ist konform zu den Spezifikationen 4.4 21). In der Regel ist in einem Kanton/in einer Regi-on die Zuständigkeit klar geregelt, die Mails könnten gezielt erfolgen.

**Anpassungsvorschlag:** Jeder KV, jede Region und die Bundesebene kann die Zuständigkeit für das Empfehlungswesen an einer Funktion [Gruppenleitung; Ausbildungsverantwortung; Beide] zuweisen. Nur die Personen mit der entsprechenden Funktion erhalten die Aufforderung für die Empfehlung bei einer Kursanmeldung. Sollte keine Person explizit definiert werden, erhalten wie bisher die Leitung und Ausbildungsverantwor-tung der jeweiligen Gruppe die Aufforderung.

### Lösung

**Man wählt im Tab Kursfreigaben eine der beiden berechtigten Rollen (Ausbildungsverantwortlicher / Kantonsleiter oder Regionalleiter aus).**

Darstellung analog Anfragen

Bei allen Varianten sollen jeweils nur die gewählten Empfehlungsinstanz Abmeldemails erhalten (siehe #26).

**Comment by RolandStuder** [comment]
Kommentar Jubla

Prio 2-3

Aktuell kann nur die Scharleitung eine Freigabe tätigen. Personen, die z.B. auf kantonaler Ebene aktiv sind und nicht mehr in der Schar sind, können nicht über die Datenbank freigegeben werden. 

Super wäre, wenn man wählen kann ob der / die kantonale Ausbildungsverantwortliche oder/und die Scharleitung die Freigabe tätigen kann. Dies spielt zum Beispiel bei einem Sicherheitsmodul eine wichtige Rolle, weil einige TN noch in einer Schar sind und andere nicht mehr.  ( siehe 1. Zugriffsberechtigungen / Rolle AV)

-- 
ToDO

- [ ]  Abklären was Zusatzaufwand wäre, das bei der Jubla auch zu tun.

**Comment by codez** [comment]
> Bei allen Varianten sollen jeweils nur die gewählten Empfehlungsinstanz Abmeldemails erhalten (siehe #26).

Fehlt noch

**Comment by philippekeller** [comment]
OK
