### ISSUE TITLE
Elternzugänge: UI-Fehler: Neues Kind registrieren und am Anlass anmelden

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#282]
Optionen können nicht oder nur via Pfeiltaste gewählt werden. Im Gif ist das UI auf dem Desktop zu sehen, auf dem Smartphone habe ich keinen Workaround gefunden.
![20230613142324](https://github.com/hitobito/hitobito/assets/1799621/ab5f0209-e588-4111-b199-7ec86a655265)
Link: https://pbs.puzzle.ch/de/groups/462/events/simple
Person zum Imitieren: https://pbs.puzzle.ch/de/groups/1079/people/4592

**Comment by richardjubla** [comment]
Betrifft auch die Jubla. 
Nicht direkt ein Bug. Aus persönlicher Empfindung aber so kompliziert/umständlich, dass es den Qualitätsansprüchen nicht genügt. 
(Workaround: Button nur als Link zur Kurs-Detail-Seite verlinken und dort die Anmeldung für Eltern und Kinder ermöglichen)

**Comment by Michael-Schaer** [comment]
Das sollte sich in dem Fall auch lösen. Siehe https://github.com/hitobito/hitobito/issues/2196#issuecomment-1731420753
