### ISSUE TITLE
Elternzugang: Rolle bei der Erst-Registrierung via Anlass

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#288]
Siehe https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946 und Antwort von Carlo: https://github.com/hitobito/hitobito/issues/2125#issuecomment-1624082949

Wenn sich bei einem Anlass eine Elternperson zum ersten mal registriert, landet sie bei der PBS im Limbo. Sie hat also keine Rolle bei der Gruppe, sondern nur eine Rolle im Anlass. Dasselbe gilt für Kinder, die durch diese Person erstellt und angemeldet werden. Bei der Jubla wird in diesem Fall die Rolle "Extern" zugeteilt.

Wunsch:
Die Person, die sich selber beim Anlass registriert, sowie Kinder, die registriert werden, sollen die Rolle "Selbstregistrierte*r" erhalten. So sind die Personen für die Adressverwalter*innen sichtbar und verwaltbar.

Abgrenzung: 
Die Rolle soll nur zugeteilt werden, wenn sich die Person beim Anlass zum ersten mal Registriert oder ein Kind registriert. Eine reine Anlass-Anmeldung eines bestehenden Accounts soll keine Rolle auf der Gruppe zur Folge haben.

**Comment by carlobeltrame** [comment]
Implementation bei der Jubla: https://github.com/hitobito/hitobito_jubla/blob/master/app/controllers/jubla/event/register_controller.rb

Gibt es die Selbstregistrierten-Rolle wirklich in jeder einzelnen Gruppe die auch Anlässe haben kann?
Und wird das nicht verwirren wenn man keine Selbstregistrierung auf der Gruppe aktiviert hat, aber nachher trotzdem solche Rollen entstehen können?

**Comment by Michael-Schaer** [comment]
Aufgrund der Diskussion am Hackathon schliesse ich dieses Ticket. Ich gehe davon aus, dass wir die Selbstregistrierung **via Anlass** vorerst nur selten verwenden werden.

@philobr @simfeld Gerne korrigieren oder wieder Öffnen bei Bedarf.
