### ISSUE TITLE
Funktion «Empfehlung zurückweisen» (PBS Ref. AKom#17) (12h)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#29]
Vorbedingung: #34 
Zuwarten mit Umsetzung -> Feedback von @philippekeller abwarten.
kann evtl. über manuelles E-Mail gemacht werden

Eine Kursempfehlung sollte von der hierarchisch nächsthöchsten Empfehlungsinstanz, bzw. für die höchste Empfehlungsinstanz vom Kursorganisator zurückgewiesen werden können. Zum Beispiel hat der Abteilungsleiter das Bemerkungsfeld leer gelassen. Die Region sollte dann die Möglichkeit haben, die Empfehlung zurückzuweisen. Dann würde die betroffene Empfehlungsinstanz ein Mail erhalten mit einem Link zur Anpassung seiner Empfehlung.
Diese Funktionalität setzt die Umsetzung der Rückmeldung AKom#23 voraus (Funktion «Empfehlung überarbeiten»).

## Schätzung 1.5 PT

**Comment by RolandStuder** [comment]
Jubla macht bezüglich Empfehlungen nichts inhaltlich auf der Datenbank und will das so beibehalten.

**Comment by psunix** [comment]
@philippekeller bitte prüfen ob es dieses Feature braucht?

**Comment by RolandStuder** [comment]
Lohnt sich nicht.
