### ISSUE TITLE
Kursqualifikation erst mit Status «Qualifikation erfasst» für TN sichtbar (PBS Ref. AKom#18) (16h)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#30]
Eine Kursqualifikation kann jetzt bereits vor oder während der Kursdurchführung vergeben werden. Erst mit einem Kursstatus «Qualifikation erfasst» oder «Abgeschlossen» darf die Qualifikation in den Perso-nendaten der TN’s ersichtlich sein.

Wir könnten auf der Kursteilnahme einfach das Flag "qualifiziert" setzen und die effektiven Qualis erst beim Statuswechsel erstellen (und sofort wenn der Status bereits "Quali erfasst"/"abgeschlossen" ist). Beim Zurücksetzen des Status werden die Qualis nicht verändert.

Hauptpunkt ist, dass manchmal Kursleiter bereits Eintragungen während dem Lager machen und sich nicht bewusst sind, dass ein Klick auf die Checkmark schon die Qualifikation erteilt.

## Schätzung 2 PT

**Comment by RolandStuder** [comment]
Schauen ob das für Jubla auch OK ist.

**Comment by codez** [comment]
Qualifikationen sind bisher nicht mit einem Kurs verknüpft. Wir könnten auf der Kursteilnahme einfach das Flag "qualifiziert" setzen und die effektiven Qualis erst beim Statuswechsel erstellen (und sofort wenn der Status bereits "Quali erfasst"/"abgeschlossen" ist).

**Comment by RolandStuder** [comment]
@philippekeller Müssen wir den Fall auch betrachten wenn der Status vom Kurs zurückgesetzt wird. Das kompliziert natürlich das ganze ein wenig.

**Comment by philippekeller** [comment]
@RolandStuder Grundsätzlich sollen die Qualifikationen 1 Mal vergeben werden, dh beim Wechsel auf den Status "Qualifikationen erfasst" sollte die Quali beim Teilnehmer angezeigt werden. Bei einem Zurücksetzten des Status sollen die Qualis nicht zurückgesetzt werden (das macht keinen Sinn, man entzieht ja keine Qualis nachträglich). Was passiert, wenn einen versehentlich falsche Quali vergeben wurde? Ist diese dann trotzdem noch bearbeitbar oder nicht?

**Comment by RolandStuder** [comment]
Feedback Jubla:

Grundsätzlich nette Idee, aber wir sehen kein Problem in der aktuellen Handhabung. Was wäre der Vorteil davon? Aus unserer Sicht wäre das nur ein zweiter Schritt. 
Evtl. könnten wir uns vorstellen, dass es praktisch ist, wenn die KHL qualifizieren kann und die AST erst den Status verändert, wenn er/sie die Anerkennung auch auf der NDBJS erfasst hat. 

Also: wenn es einfach geht, dann wäre das nice to have.

**Comment by RolandStuder** [comment]
@philippekeller Qualifikationen kann man nachträglich löschen, allerdings nicht bearbeiten. Jubla hat aber Interesse daran, Qualifikationen bearbeitbar zu machen.

**Comment by RolandStuder** [comment]
Rejected. Jubla und PBS wollen beim Prinzip bleiben, dass die Personen selbst ihre Adressangaben anpassen.

**Comment by RolandStuder** [comment]
Falsches Issues geschlossen

**Comment by RolandStuder** [comment]
Wird mit https://github.com/hitobito/hitobito/issues/286 abgedeckt.
