### ISSUE TITLE
UI Fehler durch Bootstrap Update

### ISSUE THREAD

**Issue by philobr** [hitobito/hitobito_pbs#304]
Ich fasse hier nach Absprache mit @Michael-Schaer einige UI Fehler, die ich mit dem Update von Bootstrap gefunden habe, zusammen:

~**1. Darstellung Betreuungspersonen in Lagern:**~
~Der Abstand zwischen dem Namen der Person und deren Funktion fehlt.~

![Fehler UI 1](https://github.com/hitobito/hitobito_pbs/assets/122129110/86a743c1-9a7e-4556-86a3-b25a0eb5ed06)

~**2. Aufzählung im Tab "Anfragen"**~
~Das entsprechende Zeichen der Auflistung ist auf der gleichen Ebene wie der Text, aber der Toggle ist zu tief.~

![Fehler UI 2](https://github.com/hitobito/hitobito_pbs/assets/122129110/25341e6e-e0f3-4036-a059-f2658d2adbe4)

~**3. Darstellung Zeitfenster "Verfügbare Kurse**~
~Wenn man die Kurse auflisten lässt, sind die zwei Fenster, in denen man den Zeitraum auswählen kann, durch den text "optional" stark verschoben.~

![Fehler UI 3](https://github.com/hitobito/hitobito_pbs/assets/122129110/cb802b85-6fda-4b10-bd6a-72c433add35e)

**4. Export Dropdown**
Auf einer gängigen Laptopscreen-Grösse wird der Dropdown "Export" zu weit nach rechts ausgedehnt, wenn ich über die Option "Etiketten" hovere. "Simple" Lösung wäre der Tausch von "Export" und "Liste importieren".

~**5. Meldung Voranmeldung**~
~In der Produktion ist diese Meldung gelb hinterlegt, wodurch sie klar erkennbar ist. Im Testsystem fehlt das. Ich denke, dass es Sinn macht, das so beizubehalten.~

*Testsystem:*
![Fehler UI 5](https://github.com/hitobito/hitobito_pbs/assets/122129110/38e946ba-5d02-4758-ab57-15329cba8356)

*Aktuell:*
![Fehler UI 5 - Ziel](https://github.com/hitobito/hitobito_pbs/assets/122129110/6e8bac7c-c8fd-4af4-b6ca-82de5a4550ae)

~Gleiches Verhalten ist auch bei der Meldung, welche Angaben für die Lageranmeldung noch fehlen. In der Produktion ist diese Meldung aktuell auch mit gelben Hintergrund.~

*Aktuell:*
![Fehler UI 5.1](https://github.com/hitobito/hitobito_pbs/assets/122129110/25eef554-fd3c-4111-9805-585585cf8558)

~**6. Einfärbung Dropdown bei Hover**~
~Wenn ich den Dropdown für die Spaltenauswahl in der Personenansicht in einer Gruppe öffne und über eine Option hovere, wird diese in der Testumgebung Lila eingefärbt bei schwarzem Text. Das ist schwer zu lesen wurde bisher so gelöst, dass die Textfarbe beim Hovern weiss wird.~

![UI Fehler 6](https://github.com/hitobito/hitobito_pbs/assets/122129110/e335c29f-b8b8-4d52-a3b3-d09a92469934)

~**7. Rollenauflisten mit Zugriff im Tab "Sicherheit"**~
~In der Testumgebung wird jetzt die Ladenachricht für die Auflistung, welche Rollen auf mich Zugriff haben, automatisch angezeigt, auch wenn ich den Knopf dazu nicht betätigt habe. Die Auflistung wird aber nicht geladen, somit warte ich für nichts.~

![UI Fehler 7](https://github.com/hitobito/hitobito_pbs/assets/122129110/6f6add26-ff66-46bb-81aa-b9aa0c6341a1)

**8. Fehlermeldung bei Nicht-Ankreuzen der Einverständniserklärung in der Anmeldung für einen Anlass**
Wenn ich diese Checkbox nicht anwähle, kommt die Fehlermeldung auf Englisch. Diese Übersetzung sollte angepasst werden. Ich erhalte die Meldung bei der Anmeldung für ein Lager.

![Fehler UI 7](https://github.com/hitobito/hitobito_pbs/assets/122129110/59f0d6b5-66a6-49cf-9741-f523823762f6)

Kannst du noch kurz drüber schauen @Michael-Schaer ?

**Comment by ThomasEllenberger** [comment]
> **4. Export Dropdown**
> Auf einer gängigen Laptopscreen-Grösse wird der Dropdown "Export" zu weit nach rechts ausgedehnt, wenn ich über die Option "Etiketten" hovere. "Simple" Lösung wäre der Tausch von "Export" und "Liste importieren".

Dieses Verhalten ist nicht auf das Bootstrap-Upgrade zurückzuführen und existiert auch bereits bei älteren Versionen von Hitobito.
Ich habe dafür ein neues, separates Bugticket eröffnet: [#2314](https://github.com/hitobito/hitobito/issues/2341)

**Comment by carlobeltrame** [comment]
> **8. Fehlermeldung bei Nicht-Ankreuzen der Einverständniserklärung in der Anmeldung für einen Anlass**
> Wenn ich diese Checkbox nicht anwähle, kommt die Fehlermeldung auf Englisch. Diese Übersetzung sollte angepasst werden. Ich erhalte die Meldung bei der Anmeldung für ein Lager.
> 
> ![Fehler UI 7](https://github.com/hitobito/hitobito_pbs/assets/122129110/59f0d6b5-66a6-49cf-9741-f523823762f6)

Diese Fehlermeldung kommt direkt vom Browser, wenn eine HTML5 Checkbox mit required markiert ist. Die Meldung ist immer in der Browsersprache und kann nicht angepasst werden.

**Comment by njaeggi** [comment]
Alle gemeldeten Fehler (4 und 8 aussgeschlossen) wurden behoben und werden morgen im Release dabei sein.

**Comment by philobr** [comment]
Leider wurde der 6. Punkt nicht bei allen Dropdowns geändert. Folgende weisen diesen Fehler noch auf: "Weitere Ansichten" und "Export".

**Comment by Michael-Schaer** [comment]
Punkt 2 stimmt auf der Produktion noch nicht:

![grafik](https://github.com/hitobito/hitobito_pbs/assets/1799621/7ed562e1-535d-4c6e-9952-d4adb615d896)

**Comment by philobr** [comment]
Sorry, dass das erst jetzt kommt, ich melde es aber thematisch in diesem Issue (hoffe, das passt so). In der Handyansicht wird das 2FA Feld seit dem Update zu klein angezeigt. Man sieht nicht den ganzen Code gleichzeitig.

![IMG_0874](https://github.com/hitobito/hitobito_pbs/assets/122129110/25b3d944-67a2-4d44-8dde-fb0764aaa05e)
