### ISSUE TITLE
Zusatzspalte in der Kursübersicht: Anmeldetermin (PBS Ref. AKom#20) (2h)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#31]
Zusatzspalte in der Kursübersicht (list_courses): Anmeldetermin.

## Schätzung 2h

**Comment by RolandStuder** [comment]
Vorgeschlagene Lösung:

* Bei Button Anmelden auf Übersicht daneben / darunter "bis XX.XX.XXXX" anzeigen.

**Comment by RolandStuder** [comment]
Ist Ok für Jubla.

**Comment by RolandStuder** [comment]
Moved to main Repo https://github.com/hitobito/hitobito/issues/285
