### ISSUE TITLE
Anmeldestand für alle sichtbar (PBS Ref. AKom#21) 8h

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#32]
Die Spalte «Anmeldungen» in der Kursliste sollte für alle Personen sichtbar sein. Aktuell ist sie nur für Personen mit Spezialfunktionen sichtbar.

* Anmeldestand anzeigen pro Event konfigurierbar gemacht -> ich kann bei Anmeldung also wählen, ob alle Anmeldestand sollen sehen können oder nicht (Checkbox)

## Schätzung 1 PT mit Konfgurierbarkeit

**Comment by RolandStuder** [comment]
Mit Jubla zu klären, wie sie das sehen.

**Comment by RolandStuder** [comment]
Für Jubla ok, ich schlage aber vor, das konfigurierbar zu machen, mit Defaultwert "Anmeldestand sichtbar für alle"

**Comment by philippekeller** [comment]
Konfigurierbarkeit wäre idel!

**Comment by nchiapol** [comment]
Der Cevi wäre hier auch interessiert. Ist bei uns auch Teil von hitobito/hitobito_cevi#1

**Comment by philippekeller** [comment]
OK
