### ISSUE TITLE
Verzerrung und nicht funktionieren von Radiobutton und Eingabefelder beim Erstellen von Lager

### ISSUE THREAD

**Issue by superserfer** [hitobito/hitobito_pbs#323]
### Aktuelles Verhalten

Beim Erstellen eines Lagers, sind die Radiobuttons verzehrt und sind nicht rund, aber sie funktionieren.
Die Eingabefelder für Erwartete Teilnehmende sieht auch leicht verzerrt aus und funktioniert nicht (Es lässt sich keine Teilnehmer anzahlt eintippen). Siehe Screenshot.

<img width="805" alt="image" src="https://github.com/hitobito/hitobito_pbs/assets/66847290/b142c2f4-dbcf-4de8-a860-a3c7f9ad49fa">

### Gewünschtes Verhalten

Die Verzerrung gibt es nicht mehr und die Eingabefelder für die erwarteten Teilnehmenden funktionieren wieder.

### Schritte zu reproduzieren

1. Zu einer beliebigen Gruppe gehen.
2. Zu Tab Lager wechseln.
3. Lager erstellen klicken.
4. Zu «J+S-Rahmen» und «Erwartete Anzahl Teilnehmende» scrollen.

### Wann ist der Fehler aufgetreten?

03.04.2024, beim Erstellen eines Lagers

### hitobito version

2.1.0

### Organisation

PBS/MiData

### Screenshots, weiterer Kontext

Getestet auf
**OS:** macOS 14.1.1 (23B81)
**Browser 1:** Google Chrome, Version 121.0.6167.160 (Official Build) (arm64)
**Browser 2:** Safari, Version 17.1 (19616.2.9.11.7)

<img width="805" alt="image" src="https://github.com/hitobito/hitobito_pbs/assets/66847290/b142c2f4-dbcf-4de8-a860-a3c7f9ad49fa">

**Comment by yvesflueck** [comment]
Nach Absprache im Team MiData bitte den Fall mit der erwarteten Teilnehmerzahl prioritär anschauen, da dieses Feld so nicht nutzbar ist. Eingaben sind im Feld möglich, jedoch ist das Feld zu klein als das man dort die getätigten Eingaben sehen könnte. @ThomasEllenberger könntest du dir dieses Problem noch kurz anschauen?

Bezüglich der Radiobuttons kann man sich am erstellten [hitobito-Issue](https://github.com/hitobito/hitobito/issues/2627) bezüglich UI-Fehler orientieren, es wurde auch bereits schon so aufgenommen.
