### ISSUE TITLE
Bereits freigegebene TN’s noch sichtbar (PBS Ref. AKom#22)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#33]
Beschreibung: In der Ansicht «Kursfreigeben» (pending approvals), nicht nur die offenen Empfehlungen anzeigen, sondern auch die Personen, die in den letzten x Jahren freigegeben wurden. Die Liste könnte wie folgt strukturiert werden:

![i22](https://cloud.githubusercontent.com/assets/9968417/18663792/4777a37a-7f20-11e6-9ea1-6d2aea7749ec.png)

**Liste ist nach Freigabedatum sortiert (neuestes zuoberst) und über ein Dropdown filterbar nach Kursart (nicht gruppiert wie im Mockup).
Die Personen sowie «Kurs» erscheinen als Hyperlink für einen Direktzugriff auf die Personen- oder respektive die Kursansicht.** 

## Schätzung 1 PT

**Comment by codez** [comment]
Die Unterteilung in einzelne Tabellen nach Kursart verunmöglicht eine sinnvolle Paginierung, welche hier sicher nötig ist. Das muss nochmals überdacht werden. Allenfalls ist mit einer Paginierung auch die Auswahl der Zeitspanne hinfällig.

> Die Liste der empfehlenden Personen ist an der Funktion gebunden

Wo und wie wird diese Liste verwendet? Sollen nicht einfach alle Empfehlungen der entsprechenden Ebene angezeigt werden, unabhängig welche Person diese getätigt hat? Die Sache mit den Rollen müsste zusätzlich implementiert werden und ist wohl nicht ganz trivial.

**Comment by RolandStuder** [comment]
@philippekeller Was sind hier die zu erwartenden Werte. Brauchen wir eine Pagination? Was für zahlen wären bei maximal 5 Jahren zu erwarten?

Bemerkung: Ja, es sollen einfach alle Emfphelungen der entsprechenden Ebene angezeigt werden undabhängig der Person oder? @philippekeller

**Comment by philippekeller** [comment]
@RolandStuder Ja, einfach alle Empfehlungen der entsprechnden Ebene. Die Anzahl Empfehlungen ist natürlich von der Grösse des Kantonalverbandes abhängig. Als Beispiel für einen Mittelgrossen KV: Im Aargau mache ich ca. 20-30 Empfehlungen pro Jahr, dh bei 5 Jahren 100-150...

**Comment by RolandStuder** [comment]
## Kommentar Jubla

Wir verstehen den Wunsch nicht wirklich und wissen nicht wie das Scharleitende sehen können?

-> Wir haben das Gefühl, dass dies sehr kompliziert wird und nicht für die Ewigkeit gespeichert werden muss. Achtung: Datenschutz!

---

Kommentar hitobito:

Diese Ansicht existiert bei der Jubla offenbar gar nicht, das wird nur via Mail abgehandelt (view wäre pending_approvals)

**Comment by hupf** [comment]
Mit Paginierung, aber ohne Zeitraum-Dropdown umgesetzt.

**Comment by philippekeller** [comment]
OK
