### ISSUE TITLE
KURSE: Personen können sich anmelden ohne ausgefüllte Pflichtfelder

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pbs#335]
### Aktuelles Verhalten

Gewisse Personen können sich an Kurse anmelden, ohne alle Pflichtangaben erfasst zu haben. Dies gillt jedoch nicht für alle Personen.

Beispiel:
Kurs https://pbs.puzzle.ch/de/groups/2/events/2118 hat eine Pflicht Anmeldeangabe.
![grafik](https://github.com/hitobito/hitobito_pbs/assets/100761305/f253db7e-abe5-4ccd-8a88-23087c69e283)

Hussein Kohlmann ( https://pbs.puzzle.ch/de/groups/1/people/2.html) kann sich an diesen Anlass anmelden, ohne diese Pflichtangabe auszufüllen. (Kann getestet werden indem man Hussein Kohlmann imitiert, vom Kurs abmeldet und neu anmeldet.)

Personen mit weniger Rechten können das jedoch nicht.
Beispielsweise kann sich John a (https://pbs.puzzle.ch/de/groups/2/people/3637) welcher den Kurs ebenfalls sehen kann nicht für den Kurs anmelden, ohne die Pflichtangabe auszufüllen.
![grafik](https://github.com/hitobito/hitobito_pbs/assets/100761305/2474df6e-a436-49e8-b74f-15c1cb4b1465)

### Gewünschtes Verhalten

Niemand sollte sich an Kurse anmelden können, wenn Pflichtangaben nicht ausgefüllt sind.

### Schritte zu reproduzieren

siehe oben

### Wann ist der Fehler aufgetreten?

10.07.2024

### hitobito version

2.2.0

### Organisation

PBS

### Screenshots, weiterer Kontext

Das Verhalten bestand auch schon vor dem letzten Release, kam also nicht mit 2.2.0 neu hinein.

Ich konnte das Verhalten auf keiner anderen Umgebung nachstellen.

**Comment by njaeggi** [comment]
Das Verhalten ist gewollt und ist im Core umgesetzt...

 ```
# Required questions are enforced only for users that are not allowed to add others
 entry.enforce_required_answers = true unless can?(:update, entry)
```

Solange die Person welche sich anmeldet, das Event bearbeiten kann, werden die Pflichtfelder bei den Event Questions nicht beachtet. Soll dieses Feature für die PBS überschrieben werden? @ThomasEllenberger 

Habe es mal noch auf der SWW Int getestet, mit dem Root User (oder anderen Usern welche das Event bearbeiten können) ist es möglich eine Anmeldung zu erstellen ohne ausfüllen der Pflichfragen
Event für Test: https://sww.puzzle.ch/de/groups/33/events/25

**Comment by ThomasEllenberger** [comment]
Issue Closed, da es sich um ein gewolltes Verhalten handelt.
PBS wurde entsprechend informiert.
