### ISSUE TITLE
ANLÄSSE: Anlassanmeldung Massenmutation J+S-Rahmen

### ISSUE THREAD

**Issue by yvesflueck** [hitobito/hitobito_pbs#336]
### Aktuelles Verhalten

Will man Personen per Massenmutation einem Anlass hinzufügen, bei dem unter "J+S-Rahmen" eine andere Option wie "Nicht J+S" ausgewählt ist, so erhält man zwar eine positive Rückmeldung vom System (Grünes Banner mit Erfolgsmeldung), jedoch werden die Personen nicht dem Anlass hinzugefügt.

### Gewünschtes Verhalten

Personen sind per Massenmutation unabhängig vom gewählten J+S-Rahmen einem Anlass zuweisbar.

### Schritte zu reproduzieren

1. In der PBS-Testumgebung zum folgenden Lager navigieren und den entsprechenden Account übernehmen
![image](https://github.com/user-attachments/assets/8a43ed3c-eac7-49c0-92aa-456c10c2e52a)
2. Im Anlass eine andere Option unter "J+S-Rahmen" auswählen wie  "Nicht J+S"
3. Per Massenmutation Personen zum Anlass hinzufügen
4. Wieder zum Anlass zurückkehren und im Teilnehmenden-Tab die Einschreibungen überprüfen.

### Wann ist der Fehler aufgetreten?

07.08.2024

### hitobito version

2.2.2

### Organisation

PBS

### Screenshots, weiterer Kontext

Da es sich hier um ein älteres Feature handelt bitte zuerst ungefähr einen halben Tag investieren in die Recherche, falls bis dahin nichts herauskommen würde, bitte mich kontaktieren.
@ThomasEllenberger könntest du dich bei Gelegenheit dem noch annehmen und es entsprechend weiterleiten?

**Comment by yvesflueck** [comment]
@ThomasEllenberger Ich habe noch vergessen, hier einen Zeitrahmen zu geben. Könntet ihr euch dem mal für 3 Stunden annehmen, falls es länger dauern sollte, können wir das Zeitbudget gerne nochmals besprechen.

**Comment by diegosteiner** [comment]
@ThomasEllenberger @yvesflueck 

Ich konnte hier zwei Probleme identifizieren:

1. Es werden bei der Auswahl des Lagers bei der Massenmutation nicht die korrekten RollenTypen für das Lager geladen:

![image](https://github.com/user-attachments/assets/fa4b3c10-a5e1-449a-8d30-6bc7d8893cc8)
IST

![image](https://github.com/user-attachments/assets/4059b4f0-edf7-4e06-a080-8b566654ece7)
SOLL

2. Bei Erstellen von Rollen in J+S Lagern gibt es im youth Wagon ein zwingendes Feld `j_s_data_sharing_accepted` (J+S Datenweitergabe):

```ruby
#<ActiveModel::NestedError attribute=participation.j_s_data_sharing_accepted, type=blank, options={:if=>:j_s_data_sharing_acceptance_required?}>,
   #<ActiveModel::Error attribute=j_s_data_sharing_accepted, type=muss ausgefüllt werden, options={}>
```

Hier ist die Frage, wie mit dieser Zustimmung bei Massenmutationen grundsätzlich umgegangen werden soll? @yvesflueck

**Comment by yvesflueck** [comment]
Vielen Dank für die Abklärungen hier.
In diesem Fall liegt das grundlegende Problem hier im Feld `j_s_data_sharing_accepted`. So wie ich es sehe, gibt es zwei Möglichkeiten um die Handhabung dieses Feldes zu korrigieren:
1. Bei einer Massenmutation von Teilnehmern wird das Feld defaultmässig auf `true` gesetzt und die einzelnen Personen, welche angemeldet wurden erhalten eine entsprechende Mitteilung. Diese würde dann am einfachsten als Mail an die Hauptmailadresse verschickt werden. Somit könnten die Personen ihre Anmeldung nochmals einsehen und gegebenenfalls mit den Verantwortliche, welche die Anmeldung durchgeführt haben, nach einer Lösung suchen.
2. Das Feld wird bei einer Massenmutation nicht gesetzt und die Personen werden auch nicht angemeldet. Vielmehr erhalten sie eine Einladung in das Lager, wobei sie die notwendigen Anmeldeangaben anschliessend noch selbst manuell ausfüllen müssen. Somit könnten/müssten sie das Feld selber auf `true` setzen oder aber die Einladung zum Lager ablehnen.

Bei beiden Varianten sehe ich Vor- und Nachteile. Bei der ersten Variante wird das Pflichtfeld einfach erzwungen und dass Problem würde dann anschliessend nur einfach im Nachhinein lösbar sein. Somit müsste dann aber auch bei jeder Anmeldung in ein Lager, welches bei der Anmeldung eine Pflichtangabe hat, ein Infomail ausgelöst werden und die Pflichtfrage auf einen vorher definierten Default-Wert gesetzt werden.
Bei der zweiten Variante müssten dann die entsprechenden Personen, obwohl die Anmeldung eigentlich durchgeführt wurde, diese noch manuell bestätigen. Auch hier müsste dann dieser Prozess bei jedem Lager mit einer Pflichtfrage bei der Anmeldung, durchgeführt werden. Der Vorteil hier wäre sicherlich, dass kein Default-Wert bei einer Pflichtangabe gesetzt/definiert werden müsste.

@ThomasEllenberger @diegosteiner Das sind die einzigen beiden Varianten, welche ich jetzt gesehen habe. Habt ihr evtl. noch andere Ideen, wie das umgesetzt werden könnte oder bevorzugt ihr eine der beiden vorgeschlagenen Varianten. Von der Umsetzung her denke ich, dass die erste Variante sicherlich einfacher ist, aber ich habe das Gefühl, dass die Zweite eine bessere/sauberere Lösung wäre.

**Comment by diegosteiner** [comment]
Lieber @yvesflueck 

Ich denke das fasst die Situation gut zusammen. Ich sehe noch eine 4. Variante, bei der man das Häkchen bei der Massenmutation einblenden würde, und die Lagerleitung das manuell setzen muss. Damit wäre die Verantwortung beim User und schafft transparenz.

Die Varianten würde ich so einstufen:

| Variante | Aufwand LL | Aufwand TN | Datenschutz | Umsetzung |
| ------------ | ------------------| ------------------ | ------------------ | ----------------- |
| 1. Infomail an TN | :+1:  klein | mittel | :red_circle:  | mittel |
| 2. Lagereinladung |  :+1:  klein | mittel | :green_circle:  | gross |
| 3. Fehlermeldung |  gross | :+1:  klein | :green_circle:  | :+1: klein |
| 3. Haken bei Mutation |  :+1: klein | :+1:  klein | :yellow_circle: | mittel |

Für Variante 3 wäre ein PR sogar schon bereit: https://github.com/hitobito/hitobito/pull/2822

**Comment by yvesflueck** [comment]
Dann würde ich hier eine kurzfristige Tendenz zu der 3ten Variante mit der Fehlermeldung, zu welchem es schon einen entsprechenden PR gibt sehen.
Somit könnte sicherlich der Workflow entsprechend korrigiert werden. Hier würde es sich dann auf längerfristige Sicht sicherlich auch noch anbieten, die 2te Variante mit der Lagereinladung umzusetzen, da diese in meinen Augen dann noch die sauberere Lösung wäre.
@ThomasEllenberger Könntet ihr bei Gelegenheit noch den entsprechenden PR https://github.com/hitobito/hitobito/pull/2822  reviewen und mergen, danke euch vielmals.
