### ISSUE TITLE
Funktion «Empfehlung überarbeiten» (PBS Ref. AKom#23) 8h

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#34]
Der TN-Empfehlung Kommentar soll auch nach der Freigabe überarbeitet werden können. Diese Funktionalität setzt die Umsetzung der Rückmeldung  #33 (Bereits freigegebene TN’s noch sichtbar) voraus.

* Bearbeitung nur bis zum Datum des Kursstarts möglich.
* Nur Bearbeiten des Kommentars ermöglichen (Empfehlung kann nicht entfernt werden)

## Schätzung 1 PT

**Comment by codez** [comment]
Wie wirkt sich das auf die Empfehlung von höheren Ebenen sowie auf die endgültige Freigabe aus? Werden höhere Ebenen nochmals benachrichtigt? Verstehe ich es richtig, dass eine Freigabe nur wiederum abgelehnt werden kann (und nicht umgekehrt), da in #33 nur freigegebene (und nicht abgelehnte) angezeigt werden?

**Comment by RolandStuder** [comment]
@phillipekeller Dies müssen wir noch genauer besprechen, siehe Kommentar oben.

**Comment by RolandStuder** [comment]
Wird von Jubla nicht benötigt.

**Comment by philippekeller** [comment]
OK
