### ISSUE TITLE
E-Mail Meldung bei Abmeldung eines TN geht an GL (PBS Ref. AKom#24)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#35]
**Beschreibung:** Wenn die Assistentin AuB eine Person für den Kurs abmeldet, erhalten die Vorgesetz-ten, d.h. Geschäftsleiter und Leiterin AuB ein Bestätigungsmail. Der Geschäftsleiter und die Leitung Kernaufgabe Ausbildung sollen dieses Mail nicht mehr erhalten. Somit erhält auf Bundesebene niemand mehr Abmeldemails.

**Spezifikationen:** Gemäss Spezifikationen von MiData-Ausbildung (4.13) ist es richtig so, bei einer Abmeldung werden die Kursleitung, der Kursorganisator und die AL informiert.

**Comment by philippekeller** [comment]
OK
