### ISSUE TITLE
ANFRAGE: 500er bei Aufrufen von Anfragen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pbs#354]
### Aktuelles Verhalten

Wird auf irgendeiner Gruppe der "Anfragen" Tab angewählt, generiert dies einen 500er.
Dies passiert nur wenn die Manuelle Freigabe auf der Gruppe auch aktiviert ist.

### Gewünschtes Verhalten

Anfragen Tab wird korrekt angezeigt.

### Schritte zu reproduzieren

1. Anmelden
2. Auf "Anfragen" klicken

### Wann ist der Fehler aufgetreten?

06.11.2024

### hitobito version

2.3.5

### Organisation

PBS / Core

### Screenshots, weiterer Kontext

![grafik](https://github.com/user-attachments/assets/b196d0d4-6ad1-4cf3-8ef6-8a8513ed5f83)

**Comment by superserfer** [comment]
Passiert auch, via Anfrage Link, welcher man per E-Mail erhält.
