### ISSUE TITLE
Nach Person PBS Nummer suchen (PBS Ref. AKom#25)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#36]
In den diversen Feldern, die eine Personensuche nach unterschiedlichen Attributen ermöglichen, ist die Suche nach der Personen-PBS-Nummer nicht möglich. Diese Funktionalität wäre für die Geschäftsstelle praktisch.
![i25](https://cloud.githubusercontent.com/assets/9968417/18663873/a9a34d60-7f20-11e6-9831-9aa1be661715.png)

## Schätzung 1 PT

Aber ich glaube das ist für die Variante mit Unterstützung des -

"-" mitindexieren
wenn möglich mit "-" suchbar, sonst einfach nur ohne

## Offen

- [ ] Überprüfen, wieso es auf Integration überhaupt nicht funktioniert hat https://github.com/hitobito/hitobito_pbs/issues/36#issuecomment-295731637
- [x] Grundsätzliches ermöglichen von Suche mit dashes, wird abgehandelt von #65
- [x] Ist für PBS ok, dass nur PBS Nummer nur mit Bindestrichen indexiert ist, aber Personen nicht auffindbar sind als Integer z. B. 3677

**Comment by codez** [comment]
Sollte das auch ohne Bindestriche funktionieren oder nur mit? Momentan ist diese Nummer als Zahl gespeichert, müsste für die Suche als String persistiert werden.

**Comment by RolandStuder** [comment]
@philippekeller Muss das auch mit Bindestrichen funktionieren, wahrscheinlich wäre das ohne Bindestriche ein Viertel so teuer :-)

**Comment by philippekeller** [comment]
Geht gut auch ohne, da es ja nur die Geschäftsstelle betrifft und diese Leute gut instruiert werden können.

**Comment by philippekeller** [comment]
Nicht OK: Wenn man die komplette PBS-Nummer ins Suchfeld eingibt, funktioniert es bei mir sowohl mit wie auch ohne Bindesstrichen nicht. Habe es in beiden Testumgebungen ausprobiert, daran liegt es also nicht.

**Comment by hupf** [comment]
Funktioniert tatsächlich nicht. Ich kann zwar nach einem einzelnen Part (z.B. 123 von 123-456-789) suchen, aber mit den Bindestrichen geht es nicht. Habs auch lokal reproduzieren können.

Ich bin mir fast sicher, dass es beim Review mit den Bindestrichen funktioniert hat und ohne nicht.

**Comment by hupf** [comment]
Lokal neu indexiert (``./bin/with_mysql rake ts:index``), jetzt funktionierts wieder. Wird der Sphinx Job auf Integration nicht ausgeführt?

**Comment by RolandStuder** [comment]
@philippekeller Wenn wir das Issue #65 Suche mit `-`ermöglichen behandeln, ist das gut so. Oder muss die Suche sowohl mit Bindestrichen und auch einfach mit der Zahl (ohne führende Nullen) funktionieren?

**Comment by philippekeller** [comment]
Nur mit Bindestrichen ist super.

**Comment by RolandStuder** [comment]
Ok, damit schliesse ich das Issue. Ob das mit der allgemeinen Korrektur klappt wird in #65 geprüft.
