### ISSUE TITLE
nach Kursnummer suchen (PBS Ref. AKom#26)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#37]
Im Hauptsuchfeld von MiData kann nicht nach Kursnummer gesucht werden. Diese Funktionalität wäre primär für die Kursorganisatoren und sekundär auch für die Kursteilnehmer praktisch.
![i26](https://cloud.githubusercontent.com/assets/9968417/18663880/b871e78e-7f20-11e6-8b1e-87db507f86fe.png)

Kursnummern sind unique

**Dieses Feature ist auf http://pbs.puzzle.ch/ zu testen!!!**

**Comment by RolandStuder** [comment]
## Kommentar Jubla

Gerne würden wir die Suchfunktion seit einigen Jahren anpassen und zum Beispiel nach Kursnummern suchen können. Toll wäre, wenn mit *-Funktion gesucht werden kann (das ist in NDBJS möglich). Zum Beispiel statt Jubla15-17 kann auch mit *15-17 gesucht werden. 

## Kommentar hitobito

War vorgesehen, konnte aber nicht mit dem bestehenden Budget umgesetzt werden.

**Comment by codez** [comment]
Im Master Branch. Suche ebenfalls nach Name und Gruppenname des Anlasses möglich.

**Comment by philippekeller** [comment]
Nicht OK: Funktioniert bei mir nicht, wenn die Kursnummer mit Bindestrich eingegeben wird (PBS CH JU 221-17), wenn ich nur "PBS CH JU 221" eingebe findet es den Kurs noch..

**Comment by RolandStuder** [comment]
Danke für den Hinweis. Offenbar funktionieren allgemein Suchen mit `-` nicht. Habe eine eigenes Issue dazu erstellt, werden wir fixen. siehe #65
