### ISSUE TITLE
Filter Qualifikationen mit UND-Verknüpfung (PBS Ref. AKom#27)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#38]
**Beschreibung:** Unter Ausbildung/Weitere Ansichten/Neuer Qualifikationen Filter/, wollte ich Personen rausfiltern die einen Panoramakurs besucht haben UND die Leiteranerkennung Jugendsport haben. Es nimmt nicht nur die Personen die beide Anerkennung haben, sondern auch Personen die ENTWEDER eine Leitersportanerkennung haben ODER einen Panoramakurs besucht haben.

**Anpassungsvorschlag:** die logische Verknüpfung via Button Radio oder Dropdown [UND; ODER] wähl-bar machen.

## Schätzung 1.5 PT

**Comment by philippekeller** [comment]
OK
