### ISSUE TITLE
Datum Qualifikationserhalt als Filter-Parameter (PBS Ref. AKom#28) 4h

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#39]
Unter Ausbildung/Weitere Ansichten/Neuer Qualifikationen Filter/, zusätzlicher Suchparameter: «Kurs-qualifikation x ab/bis Jahr y erhalten». Beispiele/Use Cases:
-   Liste von allen TN’s von Kurs x aus dem eigenen KV, die den Kurs in den letzten y Jahren besucht haben um Werbung für den nächsten Kurs zu machen. 
-   Liste von allen Coaches, die in diesem Jahr (y) ihre Qualifikationen in diesem Jahr verlängern müssen, um ein Reminder zu schicken.

Eigener Abschnitt "Qualifikationsjahr einschränken"

@philippekeller bitte noch definieren welche Filteroptionen zur Verfügung stehen sollen

Konkrete Filter die umgesetzt werden:
* Qualifikation A läuft zwischen X und Y ab.
* Qualifikation B ist zwischen X und Y ausgestellt worden

- > Reaktivierbarkeit muss somit aus dem Ablaufdatum zurückgerechnet werden.
- > Verlängerungen gelten als eine neu Ausstellung einer Qualifikation

## Schätzung 0.5 PT

**Comment by RolandStuder** [comment]
## Kommentar Jubla

Anpassung tönt gut!

Wir fänden es auch noch praktisch, wenn alle Experten, die in diesem Jahr ihre Qualifikation verlieren, informiert werden können.

**Comment by RolandStuder** [comment]
@codez: Ja. Verlängerungen gibt es ja nur bei J+S-Anerkennungen und dort soll die Verlängerung als "neue Qualifikation" in diesem Jahr gefunden werden.

**Comment by philippekeller** [comment]
OK
