### ISSUE TITLE
Kursliste in alphabetischer Reihenfolge (PBS Ref. AKom#29)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#40]
Die Kurse sind in der Kursliste (https://db.scout.ch/de/list_courses) in einer nicht-nachvollziehbarer Reihenfolge gelistet. Eine Alphabetische Reihenfolge würde die Kurssuche vereinfachen.

Vorschlag:

* Alphabetische Sortierung der **Kurskategorien** (es geht um die Reihenfolge der Kurskategorien, nicht der Kurse selbst).

**Comment by RolandStuder** [comment]
Alle Eventlisten sind danach sortiert, wann der Anlass beginnt.

**Comment by philippekeller** [comment]
In dem Fall ist es aber weder nach Startdatum noch alphabetisch sortiert.

**Comment by RolandStuder** [comment]
## Kommentar Jubla

Die AST haben auch bereits mehrmals über diese Kurslisten gesprochen. Die Kursliste sei wirklich nicht übersichtlich. So wie wir das sehen, ist aktuell die Kursliste nach Datum sortiert.

Wir haben uns überlegt, dass diese Ansicht mit Hilfe von Filtern übersichtlicher werden kann. Gerne würden wir zusätzlich nach Kursart sortieren können. Denn der Kursname ist ja frei wählbar und es kann sein, dass wenn nicht alle den gleichen Kursnamen erfassen, eine alphabetische Reihenfolge nicht sinnvoll ist. 

Wunsch: Sortierfunktion nach Kursart, Kursnummer, Status usw...

Info aus AST-Weiterbildung
„Suchfunktionen nach Kursnummer / Sortieren nach Kursart / J+S-Bezeichnung / Status / Datum laut Oli wird das bereits umgesetzt.“

## Kommentar hitobito

Es geht in diesem Fall um die Kursübersicht, wenn man oben in der Navigation auf Kurse klickt. Nicht um die Eventliste, z. B. Beim Kanton. Ich finde persönlich da das Konzept noch etwas verwirrend. Gerne stelle ich mal einen Vorschlag zusammen wie man das umgestalten könnte.

**Comment by kronn** [comment]
@codez war das bereits erledigt? Ich finde keine Codeänderung dazu.

**Comment by philippekeller** [comment]
OK
