### ISSUE TITLE
Funktion «Kurs duplizieren» (PBS Ref. AKom#30)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#41]
Möglichkeit, ein Kurs einfach zu duplizieren. Use case: bei der Eröffnung eines Kurses, welcher sehr similär ist mit einem bereits durchgeführten Kurs ist kann Zeit gespart werden indem die Daten des be-reits durchgeführten Kurses dupliziert werden können (insbesondere auf Grund der benutzerdefinierten Felder von grossem Interesse).

Duplizieren von:
* allen Textfeldern / Checkboxes usw.
* alle Daten
* durchgeführt von
* alle Anmeldefelder (custom fields: Angaben für Anmeldung)
* Custom fields
* Kontaktperson

Nicht duplizieren:
* LKB
* Andere zusätzliche Rollen
* Kursstatus wird auf Neu gesetzt
* Teilnehmer

Grundsätzlich innerhalb der gleichen Gruppen

Für alle Anlassarten

Duplizieren > Neuer Anlass mit vorausgefüllte Felder

Wagon Erweiterungen bedenken

Vergleichbar mit https://github.com/hitobito/hitobito/issues/86

## Schätzung 1 PT

**Comment by RolandStuder** [comment]
## Kommentar Jubla 

Jawohl! Unbedingt! Das wäre grossartig!!!

Duplizieren mit: 
Kursbestimmungen
Beschreibung
Usw.
 alles, aber alles muss auch noch anpassbar sein!!!


## Kommentar hitobito

Ja, es ergibt einfach einen neuen Kurs, den man genau gleich bearbeiten kann.

**Comment by philippekeller** [comment]
OK
