### ISSUE TITLE
Doppeladministration Vorbasiskurse (PBS Ref. AKom#31)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#42]
Die Vorbasiskurse ab 3 Tage müssen doppelt administriert werden. Eine Lageranmeldung und eine Kursanmeldung sind notwendig. Eine Lösung soll jedoch umgesetzt werden um der doppelte Eintrag von Daten zu verhindern.

Lösungsansatz (mit "Lager" abgestimmt):
-   Für Leitpfadi-, Pio- und Futurakursen kann bei der Kursart eine Option aktiviert werden «Kurs als Lager anmelden».
-   Sobald diese Option aktiviert ist erscheinen weitere Pflichtfeldern, die ausgefüllt werden müssen. Mit diesen Feldern werden die Daten erfasst, die für eine Lageranmeldung zusätzlich nötig sind.
-   Der Coach wird als «LKB» erfasst.
-   Nach der Kurserfassung besteht die Möglichkeit, aus dem Kurs eine Lageranmeldung in PDF zu generieren.
- Coach/LKB kann analog das Lager einreichen

## Schätzung 2.5 PT

**Comment by RolandStuder** [comment]
Hat Jubla diesen Fall auch?

**Comment by psunix** [comment]
Nein, Jubla hat keine Lageranmeldung

**Comment by codez** [comment]
@philippekeller Ein Lager hat noch die zusätzlichen Rollen "Leiter Sicherheitsaktivität" sowie die Betreuungspersonen für die Sicherheitsaktivitäten und den AL. 

Ausserdem erhalten der Coach und die Betreungspersonen für die Sicherheitsaktivitäten E-Mails, wenn sie zugewiesen werden, wobei der Coach seine Zuweisung zusätzlich bestätigen muss.

Sollen diese Dinge bei den Vorbasiskursen ebenfalls vorhanden sein oder können wir gewisse Abläufe vereinfachen?

**Comment by RolandStuder** [comment]
Insbesondere die Mails sind aufwändig. Z. T. werden noch bei Kursstatus Wechsel Mails verschickt, dies ist dann gar nicht möglich, weil Lager und Kurse unterschiedliche Stati haben.

**Comment by RolandStuder** [comment]
* Rolle AL braucht es nicht (wäre aber nicht so schlimm wenn er drin bleibt), aber Sicherheitsaktivitäten schon.
* Leiter / Klassenlehrer / Referent / Kurshelfer alle auf Lagerleitung in Anmeldung aufführen.
* Können auf Mails für Zuweisungen von Betreuungspersonen und Coaches.

**Comment by philippekeller** [comment]
Nicht OK: Grundsätzlich funktioniert es einwandfrei. Wäre schön, wenn bei "Betreuung" bei "Abteilungsleitung" "Abteilungsleitung/ Ausbildungsverantwortliche/r" stehen würde wie bei "Coach/LKB", wenn dies möglich ist...

**Comment by RolandStuder** [comment]
@philippekeller  

Du meinst so?

![image](https://cloud.githubusercontent.com/assets/194364/25232037/51411ca4-25da-11e7-9bc5-83e3b2abf608.png)

Soll dies im Formular auch angepasst werden?

![image](https://cloud.githubusercontent.com/assets/194364/25232107/93bc7c9a-25da-11e7-8d22-32567ab0d1ab.png)

Und darunter soll für AL anwesend / AL Besuch das wording auch angepasst werden?
z. B. AL/AV besucht Lager

Und soll das nur im Fall der Doppeladministration sein, oder kann das auch sonst beim Lager stehen?

**Comment by philippekeller** [comment]
Ja, ideal wäre überall und nur bei der Doppeladministration.
