### ISSUE TITLE
Eigene Felder für die TN-Administration (PBS Ref. AKom#32)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#43]
#Bei der Kurseröffnung können eigene Feldern (weitere Teilnehmerinformationen) defi-niert werden, welche nur für die Kursleitung, Ausbildungsverantwortung und LKB sichtbar und bearbeit-bar sind. Eine entsprechende Ansicht ermöglicht die Bearbeitung diesen zusätzlichen TN-Informationen. Diese zusätzliche TN-Informationen werden auch automatisch im Export der TN-Daten enthalten.

Beispiel use case: der Ausbildungsverantwortlicher muss heute Informationen (TN-Attributen) wie «Not-helferunterlagen eingegangen», «Kurs bezahlt», etc. verwalten. Das Ziel wäre solche Informationen in MiData verwalten zu können, um weitere externe Excel-Listen zu vermeiden.

Ich weiss das ist noch etwas vage hier. Daher bitte zwei Schätzungen. 

## Varianten:

* **Spreadsheet**: Eine wo ich direkt in der Teilnehmerliste neue Spalten anlegen kann, wie in einem Spreadsheet, welche ich frei mit Text ausfüllen kann.
* **Wie Anmeldeattribute**: Gleich wie Anmeldetattribute. Welche man genau gleich wie die Anmeldung bearbeitet. Aber halt einfach nicht für Teilnehmer sichtbar.

## Entscheidung

1. Schritt: Gleich wie Anmeldeattribute 

## Schätzung 0.5 PT

**Comment by RolandStuder** [comment]
## Kommentar Jubla

Dieses Kommentarfeld tönt spannend. Diese Idee wurde auch bei den Arbeitsstellen schon oft diskutiert und es wurde nicht als wichtig empfunden. Zum Beispiel ist das Vermerken des Notfallausweises eine Schwierigkeit. Wir haben dies in einem Kanton bis jetzt aber mal so gelöst, dass die AST den Notfallausweis als Anerkennung erfasst und so pro Person für immer sichtbar ist und nicht nur für den einen Kurs. 

-> würden wir übernehmen

**Comment by philippekeller** [comment]
OK
