### ISSUE TITLE
Schreiberechte TN-Personendaten für Hauptkursleiter (PBS Ref. AKom#33) (4h)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#44]
Oftmals findet man aber im Kurs beim Herumreichen der Adressliste raus, dass einige Angaben nicht stimmen. Da wäre es sehr praktisch, wenn dann der HKL alle inkorrekten Angaben kurz korrigieren könnte. Diese Möglichkeit für den Hauptkursleiter soll sich exklusiv auf die Kursteilnehmer beschränken.

HKL sollen Schreibrechte auf die Personendaten von den Kursteilnehmer erhalten.

## Schätzung 0.5 PT

Vor Umsetzung mit @philippekeller Rücksprache nehmen

**Comment by RolandStuder** [comment]
Beachte auch Teilnehmerimport:
https://github.com/hitobito/hitobito/issues/101

**Comment by RolandStuder** [comment]
@philippekeller : Abklären ob das auch für Coaches / Lagerleiter / Event-Hauptleiter gelten soll.

**Comment by RolandStuder** [comment]
@codez Sehe ich das richtig, dass hinzufügen zu Events, das Anfrageverfahren auslöst (ich meine das Datenschutzfeature)?

**Comment by RolandStuder** [comment]
Kommentar Jubla:

> Wir verfolgen die Idee, dass alle ihr eigenes Personenprofil aktuell halten. Alle Telefonate und Mails mit Adressänderungen werden freundlich beantwortet mit „Danke für die Info. Bitte passe die Adresse auf der jubla.db ein. So ist sie für alle Ebenen sichtbar.“

**Comment by RolandStuder** [comment]
Wird nach weitere Diskussion nicht erwünscht. Personen sollen ihre Daten selbst aktuell halten.
