### ISSUE TITLE
Mail nur bei Abmeldung von zugeteilten TN (PBS Ref. AKom#36)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#45]
**Ist-Situation:** bei jeder Abmeldung durch den Kursorganisator wird der **Kursleitung** vom System ein Mail geschickt. (auch bei nicht zugeteilten Teilnehmern)
**Soll-Situation:** nur bei der Abmeldung von bereits zugeteilten TN’s wird vom System ein Mail geschickt.

Aber nach wie vor Mail an Empfehlungsinstanzen. (falls heute so)

## Schätzung 2h

**Comment by RolandStuder** [comment]
Hier im Kontext von Abmeldungen durch Kursverantwortlichen, nicht bei Eigenabmeldung.

**Comment by RolandStuder** [comment]
Unklar: Sollen gar keine Mails mehr verschickt werden? Wenn nicht zugeteilt?

Noch klären: Wir haben die Vermutung, dass es um den den folgenden Fall geht.

* Kanton meldet Person ab.
* Kursleitung erhält ein Email dazu, obwohl er diese Person bisher noch gar nicht gesehen hat.

Lösung wäre für diesen Fall:
* Kein Mail an Kursleitung bei nicht zugeteilten TN
* Aber nach wie vor Mail an Empfehlungsinstanzen.

**Comment by hupf** [comment]
Wenn der Status einer Participation auf canceled oder rejected gesetzt wird, werden folgende Parteien benachrichtigt:
* Empfehlungsinstanzen (implementiert mit #26)
* Abeiltungsleitung (nur canceled)
* Kursleitung (nur canceled)
* Kursorganisatoren (nur canceled)

**Comment by RolandStuder** [comment]
@philippekeller Wir brauchen noch die genauen Angaben, welche der obenstehenden Rollen kein Mail und welche noch ein Mail erhalten sollen.

- Empfehlungsinstanzen (implementiert mit #26)
- Abeiltungsleitung (nur canceled)
- Kursleitung (nur canceled)
- Kursorganisatoren (nur canceled)

**Comment by RolandStuder** [comment]
@hupf Es geht tatsächlich nur um die Kursleitung, bei den anderen keine Änderungen.

**Comment by philippekeller** [comment]
OK
