### ISSUE TITLE
Ansicht auf alle Kurse für Akom (PBS Ref. AKom#13)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#46]
Für die Mitglieder der Ausbildungskommission (Standard Gremium Bundesebene) sollten alle Kurse von allen KV in der Kursliste sichtbar sein.

Manche Personen haben auf der Kursliste list_courses oben rechts ein Dropdown, wo sie auswählen können, welche Ebene sie sehen wollen, oder alle. Leute der Ausbildungskommission sollten diese auch haben. Das würde ausreichen für deren Arbeit.

* Deshalb neue Gruppe Ausbildungskomission
* Darunter Rolle "Mitglied" mit :group_read, :contact_data

**Comment by RolandStuder** [comment]
Ich nehme an, es geht hier auch um geplante Kurse, die auf der öffentlichen Kursliste nicht erscheinen.

**Comment by RolandStuder** [comment]
Manche Personen haben auf der Kursliste `list_courses` oben rechts ein Dropdown, wo sie auswählen können, welche Ebene sie sehen wollen, oder alle. Leute der Ausbildungskommission sollten diese auch haben. Das würde ausreichen für deren Arbeit.

Fragen: Welche Rollen haben diese Berechtigung?

Lösung: Neue Gruppe Ausbildungskomission mit TN (:group_read)

**Comment by RolandStuder** [comment]
Andere Variante, ist diese Auswahl einfach allen bereitzustellen, dann können sie selbst auswählen, welche Kurse sie sehen wollen.

**Comment by philippekeller** [comment]
Müsste man diskutieren. Ansicht evt. ja, aber ohne die Möglichkeit, sich auch überall selber anmelden zu können.

**Comment by RolandStuder** [comment]
@philippekeller  Man kann sich bereits heute bei allen Events frei anmelden

**Comment by philippekeller** [comment]
@RolandStuder Ja, aber da man sie nicht sieht de facto fast nicht findet, (Man müsste zur Gruppe des entsprechenden Kursträgers und dann dort unter Kurse) tun das wenige. Dies ist in unserem Sinne, da Anmeldungen von anderen Kantonalverbänden nur mit Vorabsprache über den Ausbildungsverantwortlichen des KV erwünscht sind. Wenn man nun in der Kursübersicht oben einfach lle Kurse sehen kann, dann besteht das Risiko, dass sie viele Tn im falschen Kurs anmelden, wo sie nicht hätten sollen...Müssen wir noch zusammen besprechen.

**Comment by philippekeller** [comment]
OK
