### ISSUE TITLE
Hauptebenenamen bei Eventslisten (Kurse, Lager & Anlässe) / Participation und Export anzeigen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_pbs#50]
SOLL:

* Auf Teilnehmerlisten von jeglichen Events wird neu der Hauptebenennamen von jeder Person angezeigt als letzte Spalte.
* In der Liste Export Alle Angaben wird eine Spalte mit Hauptebenennamen ausgegeben.
* In der Liste Export Adressliste wird eine Spalte mit Hauptebenennamen ausgegeben.
* Bei Kursen auf Anmeldungsscreen `/application_market` statt Gruppenname, Hauptebenenamen verwenden. Neue Formatierung: `[Hauptebenenamen] (Wohnort: [Wohnort])`
* Auf Anmeldungsseite (participation:show) auch Hauptebenenamen anzeigen (noch zu definieren wie genau)

* Im Jubla Wagon ist das schon drin, bitte sicherstellen, dass es nicht verdoppelt wird.

Teil von Issue #21 

## Schätzung 1PT

**Comment by RolandStuder** [comment]
Bitte schätzen

**Comment by codez** [comment]
Sind nur die Exporte von Event-TN-Listen betroffen oder auch die von Gruppen-Personen?

**Comment by RolandStuder** [comment]
Ist bei Jubla bereits geschehen

@codez Ja, soll auch bei Gruppen-Personen Exporten erfolgen. Eigentlich möglichst überall.

**Comment by psunix** [comment]
wird auch bei Jubla angezeigt werden. Falls dies zu doppelten Informationen führen sollte, müsste man den Jubla wagon entsprechend customizen.

**Comment by philippekeller** [comment]
OK
