### ISSUE TITLE
Empfehlungsdaten für alle Kursteilnehmer (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_pbs#51]
Für die Kursvorbereitung benötigt ein Kursleiter alle Empfehlungsdaten über alle Personen hinweg, damit er den Kurs auf die Mitglieder ausrichten kann. Ein Anklicken aller einzelnen Teilnehmer ist dafür zu mühsam. Zusätzlich braucht er auf dieser Ansicht die Kontaktdaten.

Daher zusätzliche Ansicht auf Kursen: Empfehlungen

![empfehlungen](https://cloud.githubusercontent.com/assets/194364/22779125/c49001fa-eeb9-11e6-9c65-08114d8f4efc.png)
 
teil von issue #21 

* **Wichtig: In dieser Ansicht werden auch die Neuen Daten aus https://github.com/hitobito/hitobito_pbs/issues/22 dargestellt. Absprache mit @kronn sicherstellen.**
* Einfach schauen, dass alle Daten vorhanden sind (auch Emailadressen / Telefonnummer der Personen, welche die Empfehlung abgegeben haben. Die Darstellung von @rolandstuder dann noch direkt in den Templates angepasst. 

Sichtbar für:

* KHL (Kurshauptleiter)
* LKB (Leiterkursbetreuer)
* Personen welcher Berechtigung haben Kurse zu erstellen.
* NICHT Kurshelfer

## Schätzung 1 PT

**Comment by RolandStuder** [comment]
@codez : Bitte schätzen

Meine Frage: Sind Emfehlungen im youth wagon oder ist das pro Org?

**Comment by codez** [comment]
Sind im PBS Wagon

**Comment by psunix** [comment]
hab schon mal damit angefang, jedoch dann gesehen das @kronn noch nicht fertig ist mit #22

**Comment by codez** [comment]
Berechtigungen von :show_approvals auf der TN Seite übernommen.

**Comment by kronn** [comment]
Ablehnungen werden nur beim Teilnehmer angezeigt, nicht jedoch in der Liste der Freigaben. Ich gehe davon aus, dass dieses Verhalten so gewünscht ist.

**Comment by philippekeller** [comment]
Nicht OK: Grundsätzlich schon gut, aber bitte in der Übersicht "Förderpunkte" anstatt "Schwächen" als Titel.

**Comment by RolandStuder** [comment]
Habe ein Korrekturissue dafür erstellt. siehe #64
