### ISSUE TITLE
 Zugriffsrechte Rolle «Verantwortliche/-r Ausbildung» (Akom #10)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_pbs#52]
Beschreibung: Die Rolle «Verantwortliche/-r Ausbildung» sollte Zugriffsrechte auf die Personendaten in seinem Kanton oder in seiner Region haben. Um die Arbeit richtig machen zu können (Teilnahmebedingungen für einen Kurs überprüfen/ schauen, wer die Qualifikationen hat für einen weiterführenden Kurs/...) muss er aber auf die Personendaten seines Kantons/Regions zugreifen können.

Bemerkung: könnte allenfalls durch die neu angedachte Rolle «Adressleser» gelöst werden (Siehe Pro-tokoll Advisory Board Sitzung 2016-1), insofern diese neue Rolle implementiert ist oder wird.

* Einfachste Lösungsmöglichkeit ist die Berechtigung :layer_and_below_read zu erteilen.
* Zusätzlich sicherstellen, dass er Leseberechtigung auf Kursteilnehmer hat.

**Comment by codez** [comment]
`:layer_and_below_read` für Verantwortliche Ausbildung auf Kanton und Region hinzugefügt. Lese- (und Schreib-) Berechtigungen für Kursteilnehmende auf der eigenen Ebene waren via `:layer_full` bereits vorhanden.

**Comment by philippekeller** [comment]
OK
