### ISSUE TITLE
Schwächen auf View Approvals nach Förderpunkte umbenennen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_pbs#64]
Übersicht "Förderpunkte" anstatt "Schwächen" als Titel

Betroffene view: http://pbsk.puzzle.ch/de/groups/1/events/84/approvals

Korrektur für #51

**Comment by RolandStuder** [comment]
Sollte morgen korrigiert sein

**Comment by simfeld** [comment]
@chrusu close?

**Comment by chrusu** [comment]
@simfeld merci für den hinweis, wird hiermit geschlossen!
