### ISSUE TITLE
Wording bei Doppeladministration Lager / Kurs (z. B. Vorbasiskurse)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_pbs#66]
betrifft Wording bei #42 

Wording Abteilungsleitung anpassen, bei doppelt administrierten Kursen soll Abetilungsleitung durch "Abteilungsleitung/Ausbildungsverantwortliche(r)" ersetzt werden. Sowohl in der Kurs Ansicht als auch im Edit - Modus

Show

![https://cloud.githubusercontent.com/assets/194364/25232037/51411ca4-25da-11e7-9bc5-83e3b2abf608.png](https://cloud.githubusercontent.com/assets/194364/25232037/51411ca4-25da-11e7-9bc5-83e3b2abf608.png)

Und edit:

![image](https://cloud.githubusercontent.com/assets/194364/25329106/b9ec778c-28da-11e7-807a-993db3238d37.png)

## Akzeptanzkriterien:

Wenn für den gewählten Kurstyp die Option "als Lager anmelden" aktiviert ist

* [ ] zeigt die Kursinfoseite unter Betreuung 'Abteilungsleitung/Ausbildungsverantwortliche(r)'
* [ ] zeigt das Editformular vom Kurs unter Betreuung, das wording vom obenstenstehendem Bild (überall AV/AL oder Abteilungsleitung/Ausbildungsverantwortliche(r))

Wenn für den gewählten Kurstype die Option "als Lager anmelden" NICHT aktiviert ist

* [ ]  zeigt die Kursinforseite unter Betreuung nur 'Abteilungsleitung'
* [ ] zeigt das Editformular vom Kurs unter Betreuung, das wording vom obenstenstehendem Bild

**Comment by RolandStuder** [comment]
@philippekeller Stimmt das so? Ich weiss noch nicht, ob das allenfalls sehr aufwändig das zu  ändern, insbesondere im Formular. Würdet ihr eine Lösung ohne Formularanpassung auch akzeptieren. Ich frage, dies insbesondere, weil wir noch 2 Tage Reserve haben, die wir nun nicht benötigen, weil wir kaum  Korrekturen haben. wir könnten also wohl noch etwas von #29, #30, #31 oder etwas unter Budget abschliesssen.

**Comment by philippekeller** [comment]
Stimmt so. 
Verstehe ich dich richtig: Es könnte aufwändig sein, ihr könntet es aber evt. in den 2 Tagen inkl. Formular machen? Eine Lösung ohne Formular wäre auch akzeptabel, jedoch weniger schön.

Bei #29, #30, #31: Falls davon doch noch was drinliegt wäre es schön. Die Priorität wäre entsprechend der Reihenfolge in GitHub. Aber lieber #66 inkl. Formular als eines von diesen 3. 

Unter Budget abschliessen, müssen/sollten wir nicht ;-)

**Comment by RolandStuder** [comment]
@philippekeller Genau. Danke für uns ist so die Priorisierung auch klar. Danke!

**Comment by RolandStuder** [comment]
@hupf Bitte schätzen

**Comment by olibrian** [comment]
Wurde via Transifex übersetzt.
