### ISSUE TITLE
Geburtsdatum in Personen-Liste

### ISSUE THREAD

**Issue by snapthecoder** [hitobito/hitobito_pbs#69]
In der Teilnehmer-Liste von Kursen, wird das Geburtsdatum (sortierbar) angezeigt.
<img width="1261" alt="bildschirmfoto 2017-09-28 um 14 23 07" src="https://user-images.githubusercontent.com/23396939/30966733-3b0acb8e-a45a-11e7-828b-04b361923055.png">

Wieso nicht auch in der Personen-Ansicht?

<img width="1325" alt="bildschirmfoto 2017-09-28 um 14 23 19" src="https://user-images.githubusercontent.com/23396939/30966782-64f39b7e-a45a-11e7-87d7-a8a7d64d21e6.png">

Wäre für ein praktisches Hilfsmittel bei Stufen-Übertritten (wechsel in andere Gruppe).

**Comment by RolandStuder** [comment]
@snapthecoder Ja, ds haben wir ergänzt, da das Alter oft wichtig ist für die Teilnehmer. Wobei das in Gruppen wohl genauso relevant ist. Was jemand auf der Liste braucht, ist aber wohl individuell. Wir werden vermutlich hier keine Anpassungen mehr machen und stattdessen, wenn das Thema wieder aufkommt, konfigurierbar machen, was auf der Personen/Teilnehmerlisten angezeigt wird:

siehe: https://github.com/hitobito/hitobito_cevi/issues/5

Also so etwas in der Art:

![](https://cloud.githubusercontent.com/assets/194364/23156088/d047d2e2-f815-11e6-8767-84f401537edc.png)

**Comment by carlobeltrame** [comment]
Ist inzwischen implementiert.
