### ISSUE TITLE
Feature: Krise (17h)

### ISSUE THREAD

**Issue by diegosteiner** [hitobito/hitobito_pbs#70]
# Problem

Damit ein Krisenteam schnell und zielgerichtet handeln kann, ist es auf korrekte und vollständige Informationen angewiesen. In hitobito sind Daten gespeichert, die in einem Krisenfall von hohem Wert sein können. Mit den jetzigen Bestimmungen ist des einem Krisen-Verantwortlichen aber nicht möglich, auf diese Daten zuzugreifen. Viele behelfen sich deshalb mit dem Missbrauch der Adressverwalter-Rolle.

Mit einem neuen Feature “Krise” soll dieser Fall “legal” abgedeckt werden können.

# Lösungsvorschlag

Auf der Ebene Kanton soll eine neue Rolle "Krisenverantwortlicher" eingeführt werden. Dieser soll bei allen Abteilungen des Kantons im Krisenfall Zugriff auf die Daten erhalten können. 

![pasted image 0](https://user-images.githubusercontent.com/939106/31079495-27fa1e94-a786-11e7-9a3f-f024f7804bfa.png)

Ein Krisenverantwortlicher löst "eine Krise" aus und erhält sofort Zugriff auf die Daten. Die Krisenstelle vom Kanton erhält ein Benachrichtigungs-Email. Wird die Krise nicht innerhalb eines bestimmten Zeitraums quittiert, werden weitere Schritte eingeleitet (z.B. wird die Kantonsleitung informiert, dass die Krise nicht abgesegnet wurde).

![pasted image 2](https://user-images.githubusercontent.com/939106/31079494-27f304b0-a786-11e7-8fb0-f0a27a3b5e4d.png)

Auf Gruppenebene soll angezeigt werden können, welche Rolle einen solchen Zugriff auslösen kann (nicht wie im Bild unten, wo sogar sämtliche Personen angezeigt werden).

![pasted image 1](https://user-images.githubusercontent.com/939106/31079496-27fb4cce-a786-11e7-943a-c5b836bc044e.png)

edit:

Nicht der Gruppenleiter (oder Abeilungsleiter) wird informiert, die Info geht lediglich an die Krisenstelle des Kantons (also alle die die Rolle Krisenverantwortlicher haben, sodass niemand unbemerkt alleine ein Krise auslösen kann).
In der Übersicht "Zugriff im Krisenfall" kann nicht eingestellt werden, ob jemand Zugriff haben soll; Es dient lediglich der Information.

**Comment by RolandStuder** [comment]
- Rolle Krisenverantwortlicher (2h)
- Krise auslösen Button, gibt temporären Zugriff, Bemerkung (2h)
- Zusätzliche Berechtigung (4h)
- Email an Gruppenleitung, Alert Box auf Info Seite (2h)
- Model Krise (2h)
- Krise abschliessen (Zugriff entfällt), Info an Gruppenleitung, Bemerkung (3h)
- Nach Timeout Kantonsleitung informieren, falls nicht abgeschlossen (2h)

17h

**Comment by RolandStuder** [comment]
Wir empfehlen den Krisenfall gleich/ähnlich wie den Support-Fall  abzuwickeln. Im Krisenfall könnte ein Krisenverantwortlicher z. B. den AL übernehmen. Dann kann man einiges an Aufwand sparen und hat technisch insgesamt weniger grosse Komplexität: siehe https://github.com/hitobito/hitobito/issues/356

**Comment by lukasblunschi** [comment]
Sali Roland,
ich habe mir diesen Issue und auch Issue #356 angeschaut... für einen Krisenfall finde ich aber das Vorgehen wie in diesem Issue (also wie von Diego Steiner oben beschrieben) besser.
Es hat den Vorteil das im Vorfeld einer Krise schon klar ist welche Person spezielle Zugriffsrechte bekommen würde. Bei einer Impersonierung müsste zuerst noch herausgefunden werden, was für eine Person man "übernehmen" möchte.
Weiter können auch die Aktionen des Krisenverantwortlichen als seine eigenen Aktionen geloggt werden und müssen nicht vom "übernommen" Benutzer unterschieden werden.
viele Grüsse,
Pi

**Comment by RolandStuder** [comment]
Gemäss Besprechung mit Adrian Anderegg stellen wir dieses Issue zurück.

**Comment by diegosteiner** [comment]
Wir haben das Issue nochmals mit diversen betroffenen Parteien besprochen und haben uns auf Folgendes verständigt:

Das Feature orientiert sich grundsätzlich am oben genannten Lösungsvorschlag, mit nachfolgenden Änderungen:

* Nicht der Gruppenleiter (oder Abeilungsleiter) wird informiert, die Info geht lediglich an die Krisenstelle des Kantons (also alle die die Rolle Krisenverantwortlicher haben, sodass niemand unbemerkt alleine ein Krise auslösen kann).
* In der Übersicht "Zugriff im Krisenfall" kann nicht eingestellt werden, ob jemand Zugriff haben soll; Es dient lediglich der Information.

@adriananderegg Bitte bestätigen

**Comment by adriananderegg** [comment]
@diegosteiner passt
@RolandStuder für unsere Besprechung morgen. PBS Release 2018-1

**Comment by RolandStuder** [comment]
Wichtiger Apsekt ist, dass eine ausglöste Krise auch angescahtu werden muss, jemand muss bestätigen dass das ok war.

**Comment by RolandStuder** [comment]
@Michael-Schaer 

Fragen zur Krise

* Wird wirklich eine neue Rolle eingefüht? Es gibt bereits die Rolle: Verantwortlicher Krisenteam. Wenn ja, dann wie ist die Bezeichnung? Und welche weiteren Berechtigungen soll diese Rolle haben?

> Wird die Krise nicht innerhalb eines bestimmten Zeitraums quittiert, werden weitere Schritte eingeleitet (die Kantonsleitung  wird informiert, dass die Krise nicht abgesegnet wurde).

* Ist das noch aktuell, muss die Krise nicht immer quittiert werden von der entsprechenden Person? Wer quittiert Krise, die auslösende Person? die Kalei?

* Wer alles darf Krisen auslösen? 
  * Kanton::Verwantwortlicher_Krisenteam
  * NICHT: Kanton::Mitglied_Krisenteam?

* Wer darf die Krise abschlissen?
  * Jeder der sie auslösen darf? 
  * Nur derjenige der sie ausgelöst hat?
  * Jemand anderes als der sie ausgelöst hat?

* Wer soll im Krisenfall notifiziert werden?
  * Kanton::Sekretariat? / Kanton::Kantonsleiter?
  * Alle anderen Verantwortlicher_Krisenteam

* Muss beim Erstellen der Krise eine Bemerkung hinzugefügt werden, oder ist diese optional?

* Muss beim Abschluss der Krise eine Bemerkung hinzugefügt werden, oder ist diese optional?

* Wo soll ich diese Bemerkungen dann sehen können?

* Gemäss der Darstellung, muss eine Krise nur nach Ablauf einer gewissen Frist quittiert werden:
   * Wie lange ist diese Frist?

Ich hatte etwas Mühe die Fragen zu formulieren, aber insgesamt, muss das noch sauberer definiert werden, in welchem Fall welche Rollen was machen, und wann wirklich informiert wird und wer. Es gibt ja grundsätzlich drei Schritte:

* Krise auslösen (Wer darf das? Wer wird informiert?)
* Kise abschliessen (Wer darf das? Wer wird informiert?)
* Krise quittieren, falls Timeout erreicht ist (Wer darf das, Wer wird informiert)

Wäre super, wenn man das Flowdiagramm ergänzen/korrigieren könnte mit diesen Punkten.

**Comment by Michael-Schaer** [comment]
Ich habe die Fragen aufgenommen und werde diese intern abklären.

**Comment by Michael-Schaer** [comment]
#### Begriffe
Auf der Bundesebene gibt es drei Rollen, die für die Krise wichtig sind. Ich nenne diese der Einfachheit halber nur "[Bund::Krisenrollen]". Die Rollen sind folgende:
- Bund::Mitglied_Krisenteam (Leitung Krisenteam, Barny)
- Bund::Geschäftsleiter (Verantwortlich Krisenmanagement, Wodka)
- Bund::Leitung Kernaufgabe (Krisenkommunikation, Capri)

#### Wer alles darf Krisen auslösen?

Kanton::Verwantwortlicher_Krisenteam, Kanton::Mitglied_Krisenteam, [Bund::Krisenrollen] (Für Ausnahmefälle)

#### Warum quittieren? Wer quittiert die Krise?

- Quittieren dient der Absicherung, dass sich niemand zu Unrecht Daten beschafft
- Nur [Bund::Krisenrollen] können quittieren
- Es darf nie die Person die Krise quittieren, die sie ausgelöst hat
- Es gibt eine einfache Liste mit offenen Krisen (Datum, Person, Abteilung, Link «Quittieren»).

#### Wer darf die Krise abschliessen?

Der Zugriff wird automatisch nach 72h wieder entfernt. Danach kann die Krise direkt wieder eröffnet werden, wenn Bedarf besteht.

#### Wer soll im Krisenfall notifiziert werden?

- [Bund::Krisenrollen], Kanton::Mitglied_Krisenteam, Kanton::Verantwortlicher_Krisenteam
- Die E-Mail enthält Informationen zum Zugriff (Datum, Person, Abteilung) 

#### Muss beim Erstellen der Krise eine Bemerkung hinzugefügt werden, oder ist diese optional?

Nein, Informationen zur Krise sind sehr diskret zu behandeln, derjenige der die Krise auslöst soll direkt und ausführlich mit der quittierenden Instanz kommunizieren. Bemerkungen sind nicht nötig.

#### Gemäss der Darstellung, muss eine Krise nur nach Ablauf einer gewissen Frist quittiert werden: Wie lange ist diese Frist?

Ja, die Krise kann innert 14 Tagen quittiert werden. Leitung und Krisenteam des Kantons werden bei der Quittierung benachrichtigt. Wenn die 14  Tage ohne Quittierung ablaufen, wird der Fall automatisch abgeschlossen, und die Benachrichtigung erstellt. So wird sichergestellt, dass die KVs innerhalb der Frist über den Vorfall informiert werden. 

#### Zugriff im Krisenfall
Es würde auch eine allgemeine Info reichen, welche Rollen im Krisenfall zugreifen können.

**Comment by RolandStuder** [comment]
Zum präzisieren aus dem Gespräch mit Michael Schär:

- Bund wird immer informiert
- Quittieren bedeutet, wir informieren Kantonsleitung (Kanton::Kantonsleitung).
- Es gibt keine Liste von offenen oder abgeschlossenen Krisen. Die Krisen werden direkt auf der Abteilung quittiert.

**Comment by RolandStuder** [comment]
Die Person die die Krise auslöst ist massgebend, wer informiert wird, bei einem Kanton, die anderen Kantonskrisenpersonen. Beim Bund die Bundeskrisenrollen.

Beim quittieren, wird beim Kanton zusätzlich, die Rolle Kanton::Kantonsleitung informiert.
Beim Bund niemand zusätzlich.

**Comment by RolandStuder** [comment]
Fragen:

- Bei Auslösen werden alle informiert, auch Bund? Das abklären, was passiert, wenn Krise auf Kanton ausgelöst wird? Was wenn von Bund?
- Quittieren, soll nur der Bund können? Also nie Kantonsleitung?
- Müssen mehrere Personen Zugriff haben können? Button -> Ich will auch Zugriff...
- Auf welchen Gruppen darf ich Krisen auslösen? -> wegen kantonsfremden?
- Was ist der Sinn vom Quittieren?

**Comment by RolandStuder** [comment]
* Wieso Krise nach 72h wieder eröffnen, sollte nicht beim Abschliessen dieser Zugriff entfernt ?
* Was ist der Unterschied zwischen Abschliessen und Quittieren?

**Comment by RolandStuder** [comment]
- Krise nicht in fremden Kantonen, auf eigenem Kanton aber möglich, Bund kann überall...
- Wenn eine Krise ausgelöst wird, werden NUR Bund::Leitung Kernaufgabe Kommunikation / neue Rolle Bund::Krisenteam Verantwortlicher notifiziert
- Krise muss quittiert werden einer der Bundesrollen und nur von diesen quittiert werden, dann bleibt es offen
- Geht Zugang nach 72h weg, er kann aber neue Krise auslösen. Es passiert ja auch nicht weiteres...
- Quittierung erteilt längeren Zugriff... XX 1 Woche -> gewisse Kontrolle, nachträgliche Quittierung ist nicht notwendig.
- Krise muss auch auf Kanton und Bund, Kantonkrisenverantwortlicher, kann nur auf Abteilung.
- Krisenteam Bund sollen es alle können.

Auf Bund dürfen alle Krisenteam Mitglieder eine Krise auslösen, auf Kanton nur Verantwortliche

**Comment by RolandStuder** [comment]
Zusammenfassung:

Krise kann von folgenden Personen ausgelöst werden:

## Auf Bundesebene

- Bund::Leitung Kernaufgabe Kommunikation
- Bund::Verantwortlicher_Krisenteam (Neue Rolle anzulegen)
- Bund::Mitglied_Krisenteam

Diese Rollen können auf beliebigen Ebenen eine Krise auslösen.

## Auf Kanton

- NUR Kanton::Verantwortlicher_Krisenteam

Diese Rollen können nur auf Abteilungen, die zu ihrem Kanton gehören Krisen auslösen. Nicht auf eigenem Kanton und auch nicht auf anderen Abteilungen.

## Was passiert bei Auslösung:

- Notifikations-e-Mail an folgende Rollen, unabhängig davon wer die Krise ausgelöst hat:
  -  Bund::Leitung Kernaufgabe Kommunikation
  -  die neue Rolle Bund::Krisenteam Verantwortlicher
- Das e-Mail enthält Zeit und Personenangaben von der auslösenden Person an, inkl. für welche Ebene die Krise ist(Abteilung), bitte auch Link auf die Infor Seite der betroffenen Gruppe.

Auf Kantonsebene wird NIEMAND informiert, Krisenverantwortliche können ihr Team selbst informieren, falls sie das wollen, gleiches gilt für Kantonsleitende.

## Weiterer Ablauf

### Zugriff

- Die Person die Krise ausgelöst hat, erhält vollen Zugriff auf diese Abteilung (:layer_full_and_below).
- Der Zugriff verfällt nach 72h

### Quittieren

- In den 72h kann die Krise quittiert werden, nur durch Bund::Leitung Kernaufgabe Kommunikation und Bund::Krisenteam Verantwortlicher
- Beim Quittieren wird ein e-Mail mit an Bund::Leitung Kernaufgabe Kommunikation und Bund::Krisenteam Verantwortlicher verschickt (mit gleichen Angaben von auslösender Person und der quittierten Personen)
- Eine Quittierung gibt der Krise den Status quittiert und verlängert den Zugriff auf 7 Tage (Verlängerung um 4 Tage).
- Nach 72h kann eine Krise nicht mehr quittiert werden. 

### Mehrere Krisen

Man kann nicht gleichzeitig mehrere Krisen auslösen. Entweder ist die Krise nicht aktiv, oder aktiv oder quittiert.

@janissbinder Hier die zusammenstellung was jetzt gilt.

**Comment by RolandStuder** [comment]
Ja, es erfolgt keine automatische Quittierung. Quittierung ist lediglich eine Verlängerung des Zugriffs mit dem Krisenfeature.

Aber es gibt noch etwas zu ergänzen:

In dem Fall, dass die **Krise von der Bundesebene** ausgelöst wird, soll der **Verantwortliche Krisenteam,** auf der **Kantonsebene** (zu welcher die Abteilung gehört)  per e-Mail notifiziert werden. . Einfach, damit jemand mitbekommt, wie häufig die Bundesebene die Funktion verwendet.
 
**Diese soll beim Abschluss der Krise** and den «Verantwortlicher Krisenteam» des betroffenen Kantons verschickt werden und soll im Wesentlichen den folgenden Text enthalten: 
«Auf der Abteilung XY wurde eine Krise durch das Krisenteam der Bundesebene ausgelöst».
 
Es haben nicht alle Kantone die Rolle «Verantwortlicher Krisenteam» vergeben, die ist aber in ihrer eigenen Verantwortung.

**Comment by janissbinder** [comment]
Ich konnte die zwei Ergänzungen noch erledigen. Es gibt aber noch ein paar andere Dinge die noch offen sind bei diesem Feature:

* crises_controller#acknowledge - Permission eintragen
* crisis_mailer#triggered - recipients anpassen und Test anpassen ('Existierenden incompleted spec überschreiben')
* Es failen allgemein noch ein paar tests welche durchlaufen sollten.
* Es wäre allgemein sinnvoll das feature noch einmal durchzuschauen und zu überprüfen ob alles wie gewünscht funktioniert.. Vielleicht allgemein das Ticket noch summieren, um klar zu sehen was eigentlich alles erwartet wird?

**Comment by janissbinder** [comment]
### HINWEIS
Beim weiter entwickeln muss auch der entsprechende core Branch ausgecket werden (feature/70_crisis). Dort sind Erweiterungen vorhanden welche für dieses Ticket verwendet werden.

**Comment by Michael-Schaer** [comment]
Merci für die Umsetzung! Grundsätzlich ist die Funktion schon sehr gut umgesetzt, wir haben allerdings noch zwei Probleme gefunden. Hier meine Rückmeldungen in Absprache mit dem Krisenteam der PBS:

#### Krisen werden nur pro Abteilung ausgelöst
In der jetzigen Umsetzung können Krisen auf Ebene Bund und Kanton ausgelöst werden. Dadurch werden die Daten aller darunterliegenden Abteilungen sichtbar. So wird eigentlich das ganze Berechtigungssystem ausgehebelt und das ist nicht die Idee dieser Funktion.

Eine Krise wird immer pro Abteilung ausgelöst und berechtigt die auslösende Person dazu, die Daten der entsprechenden Abteilung zu sehen. 

#### E-Mail-Bestätigung bei Auslösung durch Bundesebene
Wenn jemand vom Kanton die Krise auslöst, wird bereits eine E-Mail an die Bundesebene verschickt. Dort wurde das tiptop umgesetzt. Wenn allerdings jemand von der PBS eine Krise auslöst, so wird noch keine E-Mail generiert.

Konkret müsste dies, wie im Kommentar von Roland beschrieben, umgesetzt werden: 
> 
> In dem Fall, dass die Krise von der Bundesebene ausgelöst wird, soll der Verantwortliche Krisenteam, auf der Kantonsebene (zu welcher die Abteilung gehört) per e-Mail notifiziert werden. Einfach, damit jemand mitbekommt, wie häufig die Bundesebene die Funktion verwendet.
> 
> Diese soll beim Abschluss der Krise an die «Verantwortlicher Krisenteam» des betroffenen Kantons verschickt werden und soll im Wesentlichen den folgenden Text enthalten:
> «Auf der Abteilung XY wurde eine Krise durch das Krisenteam der Bundesebene ausgelöst».
> 
> Es haben nicht alle Kantone die Rolle «Verantwortlicher Krisenteam» vergeben, die ist aber in ihrer eigenen Verantwortung.

**Comment by Michael-Schaer** [comment]
Merci für den Fix. Abnahme PBS ist erfolgt!
