### ISSUE TITLE
Mitglieder des Gremiums sehen keine Personen unterhalb (3h)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito_pbs#71]
![grafik](https://user-images.githubusercontent.com/9968417/31316483-c1b09e76-ac2e-11e7-919e-8f7a44cafaf1.png)

Die Mitglieder eines Gremiums sehen keine Personen unterhalb. Dazu müssen sie heute direkt mit einer Rolle in der übergeordneten Gruppe hinzugefügt werden. Dies führt zu diversen Personen mit sonderbaren Rollen. 

Beispiel: 
Die Komission der Wolfsstufenleiter innerhalb des Kantons möchte alle Leiter in den Wolfsstufen sehen. Diese sind typischerweise in einer Gruppe "Wölfe" unterhalb der Abteilung als Leiter aufgeführt. 

Lösungsvorschlag:
neuer Gruppentyp "Komission", welcher den Mitgliedern die gleichen Rechte vergibt, wie wenn sie auf Ebene der darüberliegenden Gruppe eine entsprechende Rolle inne hätten.

**Comment by RolandStuder** [comment]
Variante A: Mehr :contact_data vergeben (1h)
Variante B: Neuer Gruppentyp / Rollen mit :layer_and_below_read (3h)

**Comment by RolandStuder** [comment]
Gemäss Besprechung mit Adrian Anderegg Variante B

**Comment by RolandStuder** [comment]
@adriananderegg Sollen wir diese Gruppenart nur auf dem Kanton einführen oder auch auch auf Region und Nationaler Ebene?

Dieses Issue wird abgelöst durch https://github.com/hitobito/hitobito/issues/422
