### ISSUE TITLE
Rolle Ausbildungsverantwortlicher auf Abteilungsebene

### ISSUE THREAD

**Issue by simfeld** [hitobito/hitobito_pbs#76]
Aktuell können nur die Rollen Abteilungsleiter bzw. Abteilungsleiter Stv. Empfehlungen für Kursanmeldungen abgeben. Es wäre nützlich, eine Rolle Ausbildungsverantwortlicher zu haben mit der Berechtigung :approve_applications, die man vergeben könnte falls diese Aufgabe nicht vom AL erledigt wird.

**Comment by adriananderegg** [comment]
@Michael-Schaer nimmst du das in den Backlog auf, zur Diskussion mit er AKom?

**Comment by simfeld** [comment]
@adriananderegg Ich kann auch versuchen einen PR zu schreiben, falls mir jemand ein wenig Starthilfe geben könnte (habe ein wenig Programmiererfahrung, aber nicht mit Ruby/Rails).

**Comment by RolandStuder** [comment]
@simfeld technisch ist das schnell gemacht, ist eher eine inhaltliche Frage.

Für dich als Tip, wenn du es mal ausprobieren möchtests:

Du müsstest hier eine neue Rolle anlegen:

https://github.com/hitobito/hitobito_pbs/blob/master/app/models/group/abteilung.rb

- Einerseits musst du die Klasse anlegen, andererseits am Ende in die Rollenaufzählung aufnehmen.
- Weiter muss du für die Mehrsprachigkeit in https://github.com/hitobito/hitobito_pbs/tree/master/config/locales in allen Sprachen in den entsprechenden model files die Rolle ergänzen.

Mit den passenden Berechtigungen, die Berechtigungen sind hier beschrieben: https://github.com/hitobito/hitobito/blob/master/doc/architecture/08_konzepte.md#berechtigungen

Grundsätzlich findest du du Infos für das Setup hier:
https://github.com/hitobito/hitobito/blob/master/doc/development/01_setup.md

**Comment by simfeld** [comment]
@RolandStuder Vielen Dank für die Hinweise! Werde es bei Gelegenheit mal ausprobieren.

**Comment by Michael-Schaer** [comment]
Hallo zusammen. Ich habe das in den Backlog aufgenommen. Ja, das Thema sollten wir mit der AKom besprechen, bevor wir es umsetzen. Das würde sich aber auch gut für den Hackathon im September eignen.

**Comment by simfeld** [comment]
@RolandStuder habe einen PR erstellt #77. Habe es einfach lokal mit Durchklicken ein wenig getestet.

Folgende Fragen sind aufgetaucht:
- Gibt es spezifische Test- oder Dokumentationstasks welche man vor einem PR durchführen sollte?
- Zum Teil gibt es alerts mit einer Message "AVOID eager loading detected". Was bedeutet dies, bzw. kann man das ignorieren?
- Zugang zur Testumgebung habe ich mir via "Passwort vergessen?" auf hitobito-pbs@puzzle.ch verschafft. Ist das der way to go?

Danke für deine Hilfe :-)

**Comment by simfeld** [comment]
@Michael-Schaer gibt es diesbezüglich eine Rückmeldung der AKom?

**Comment by simfeld** [comment]
Rückmeldung der AKom, MiData-Konferenz 2018

> Wir sind der Meinung, dass auf Stufe Abteilung der AL für die Ausbildungskoordination zuständig sein sollte.
Demnach soll die Freigabe auch beim AL und/oder seinem Stv. bleiben.
In unseren Augen würde so eine Funktionalität geschaffen, die vom ursprünglich angedachten Prozess her nicht nötig ist bzw. nicht nötig sein sollte.
Wenn es tatsächlich so wäre, dass es einen separaten Ausbildungsverantwortlichen in der Abteilung gibt, dann sehen wir das Verwenden der Rolle "AL-Stv." nicht als Missbrauch.
Dieser wirkt ja in dem Sinne stellvertretend für den AL.

Ich schliesse somit dieses Issue und den zugehörigen PR.
