### ISSUE TITLE
Batchoperation zum Hinzufügen von Lagerteilnehmern

### ISSUE THREAD

**Issue by simfeld** [hitobito/hitobito_pbs#79]
Teilnehmer können zu einem Lager via "Person hinzufügen" hinzugefügt werden. Jedoch geht dies nur mit Einzelabhandlung, soweit ich weiss. Bei einem Lager mit 120 Teilnehmern ist dies relativ mühsam. Schön wäre eine Batchoperation, bei der z.B. in einer Liste aller Personen der Ebene wo das Lager eingetragen ist (sowie den Unterebenen) Checkboxes gesetzt werden können, und die dabei ausgewählten TNs alle auf einmal hinzugefügt werden können.

**Comment by adriananderegg** [comment]
Dies ist in der Tat ein Thema, das relativ weit oben im PBS Backlog steht. 
Siehe auch im [Hitobito-Forum](https://hitobito.discoursehosting.net/t/massenmanipulationen-auf-personenlisten/33) (aktuell der Ort, wo seitens Hitobito die längerfristigen Themen diskutiert werden). 

Den PBS Backlog findest du übrigens [hier](https://trello.com/b/bHJxD4Zm/team-midata-features). Under geplant ist auch die Batchoperation für Funktionsänderungen und Teilnahmen an Anlässen aufgeführt.

**Comment by simfeld** [comment]
@adriananderegg Danke für den Hinweis. Dann werde ich nächstes Mal zuerst im Forum bzw. auf Trello nachschauen, bevor ich voreilig ein Issue eröffne :smile:
