### ISSUE TITLE
Eltern mit mehreren Kindern ?

### ISSUE THREAD

**Issue by bufferoverflow** [hitobito/hitobito_pbs#92]
Aktuell ist es nicht möglich mehrere Kinder mit einem Login auf db.scout.ch zu verwalten.

Es ist üblich das die Kinder insbesondere in jungen Jahren ( < 16 Jahre) den Account nicht selbst verwalten. Eine Möglichkeit den Kinder später ein separates Login zu erstellen sobald eine persönliche email addresse hinterlegt ist wäre sinnvoll.

**Comment by Vento-Nuenenen** [comment]
Hallo

Die Informationen über den Stand der Elternlogins findest du im Issue https://github.com/hitobito/hitobito/issues/603 . Ich nehme an, dass ist was du meinst?

Die PBS ist an der Prüfung der Anforderungen am Arbeiten. Ob und wann das kommt ist aber noch Offen..

LG
Vento

**Comment by bufferoverflow** [comment]
Vielen Dank @Vento-Nuenenen ! Das ist genau das issue.
