### ISSUE TITLE
Testsystem 404

### ISSUE THREAD

**Issue by Vento-Nuenenen** [hitobito/hitobito_pbs#97]
Das Testsystem der PBS hat zwischendurch ein Problem.
Dann wird einige Sekunden lang nur noch ein Error 404 angezeigt, egal auf welche Seite man zugreifen will.
Kurz darauf gehts dann jeweils wieder.

**Comment by olibrian** [comment]
Auf der Testumgebung kann es zu Unterbrüchen kommen. Beispielsweise wenn eine neue Versionen eingespielt wird. Der Unterbruch sollte im Zeitbereich von 1 bis 5 Minuten sein bis die Applikation wieder zur Verfügung steht. Natürlich könnte ein unterbruchfreies Deployment oder eine zweite Umgebung bereitgestellt werden - dies erfordert aber entsprechende Aufwände.

**Comment by Vento-Nuenenen** [comment]
Das solche ausfälle vorkommen und das es sich um ein Testsystem handelt, ist mir klar.
Es sind aber wohl nicht solche ausfälle... Es kommt ca. jede halbe Stunde vor und hällt dann für etwa 1 Minute an, dass nur noch eine 404-Seite angezeigt wird. Jedoch auch nicht die von Hitobito.

**Comment by Michael-Schaer** [comment]
Die Ausfälle kommen wirklich sehr häufig vor, jedoch nicht regelmässig bei einer bestimmten Aktion. Ich vermute, dass es mit dem "verschieben" des Testsystems zu tun hat (vor 2-3 Wochen, was genau die Änderung war, weiss ich nicht). Wir wären froh, wenn ihr das fixen könntet.

**Comment by kronn** [comment]
Merci für die genauen zeitliche Einordnung des Fehlers.

Das Verschieben des Testsystem war auf eine andere, jedoch technisch gleiche Platform und beinhaltete auch den Wechsel einiger Konfigurationen. In anderen Kontexten hatten wir kein Problem mit dem neueren Setup. 

Ich habe mit unserem Middleware-Team jetzt einen Check eingerichtet, der das mínütlich beobachtet. Ich hoffe, dass wir das wir damit genug Informationen bekommen, das zu beheben.

**Comment by Michael-Schaer** [comment]
@kronn Ist bei den Checks etwas herausgekommen?

**Comment by olibrian** [comment]
Die Integrationsumgebung hat mehr Ressourcen bekommen.
